#!/usr/bin/env python3
"""Expert 10: Training Pipeline Analysis"""

import os
import json
import numpy as np

REPORT = os.path.join(os.path.dirname(__file__), 'expert_10_training_pipeline.md')
VIBROSENSE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESULTS = os.path.join(VIBROSENSE, '10_fullchain/results')

def main():
    lines = []
    L = lines.append

    L("# Expert Report 10: Training Pipeline Analysis")
    L("")
    L("## 1. Training Pipeline Overview")
    L("")
    L("File: `09_training/train.py`")
    L("")
    L("### Pipeline Steps")
    L("1. Load data (CWRU .mat files or synthetic generation)")
    L("2. Segment into 0.5s windows (6000 samples at 12 kHz)")
    L("3. Extract 8 features per window:")
    L("   - Features 0-4: Band envelope energy (5 BPF bands)")
    L("   - Feature 5: Broadband RMS")
    L("   - Feature 6: Crest factor (peak/RMS)")
    L("   - Feature 7: Kurtosis")
    L("4. Normalize features with MinMaxScaler to [0, 1]")
    L("5. Train LogisticRegression with quantization-aware hyperparameter tuning")
    L("6. Quantize weights to 4-bit (16 levels)")
    L("7. Export to SPICE format")
    L("")

    L("## 2. Feature Extraction Details")
    L("")
    L("### Band-Pass Filtering (Python)")
    L("- 2nd-order Butterworth band-pass (scipy)")
    L("- Bands from config: [100-500], [500-1500], [1500-3000], [3000-4500], [4500-5900] Hz")
    L("")
    L("### Envelope Detection (Python)")
    L("- Full-wave rectification: `np.abs(filtered)`")
    L("- 1st-order IIR LPF with alpha = 1 - exp(-1/(fs*tau))")
    L("- tau = 1/(2*pi*envelope_lpf_hz)")
    L("- envelope_lpf_hz = 10 Hz (from config)")
    L("- Feature value = mean(envelope) over 0.5s window")
    L("")
    L("### Key Difference: Python vs Analog")
    L("")
    L("| Aspect | Python Training | Analog Chain |")
    L("|--------|----------------|--------------|")
    L("| BPF order | 2nd-order Butterworth | 2nd-order Tow-Thomas |")
    L("| BPF bands | [100-500] etc | f0=227, 1001, 3162, 7236*, 14639* Hz |")
    L("| Rectification | Full-wave (abs) | Half-wave (OTA) |")
    L("| Envelope LPF | IIR, fc=10 Hz | Gm-C, fc=92 Hz |")
    L("| Feature | mean(envelope) | DC voltage at end of sim |")
    L("| Window | 0.5 seconds | 0.2 seconds |")
    L("| RMS | np.sqrt(mean(x^2)) | MOSFET square-law |")
    L("| Crest | max(abs(x))/RMS | Peak detector / (RMS computation) |")
    L("| Kurtosis | scipy.stats.kurtosis | rms_ref (constant!) |")
    L("")
    L("*BPF4 and BPF5 are detuned in analog due to shared bias (see Expert 02)")
    L("")

    L("## 3. Normalization Analysis")
    L("")
    L("The training pipeline uses `MinMaxScaler`:")
    L("```python")
    L("feature_norm = (feature_raw - min) / (max - min)")
    L("```")
    L("This maps each feature independently to [0, 1].")
    L("")

    # Load trained weights to find normalization params
    tw_path = os.path.join(VIBROSENSE, '09_training/results/trained_weights.json')
    if os.path.exists(tw_path):
        with open(tw_path) as f:
            tw = json.load(f)

        norm = tw.get('normalization', {})
        if norm:
            L("### Normalization Parameters (from trained model)")
            L("")
            feat_names = ['BPF1 env', 'BPF2 env', 'BPF3 env', 'BPF4 env', 'BPF5 env',
                          'RMS', 'Crest', 'Kurtosis']
            L("| Feature | Min | Max | Range |")
            L("|---------|-----|-----|-------|")
            min_vals = norm.get('min', norm.get('data_min', [0]*8))
            max_vals = norm.get('max', norm.get('data_max', [1]*8))
            if isinstance(min_vals, list) and len(min_vals) >= 8:
                for i in range(8):
                    rng = max_vals[i] - min_vals[i]
                    L(f"| {feat_names[i]:9s} | {min_vals[i]:.4f} | {max_vals[i]:.4f} | {rng:.4f} |")
            L("")

    L("## 4. SPICE Export: Voltage Mapping")
    L("")
    L("From `export_spice_vectors()` in train.py:")
    L("```python")
    L("voltage = X_test_norm[idx, feat] * 1.8  # scale to 0-1.8V")
    L("```")
    L("")
    L("So a normalized feature of 0.0 -> 0.0V, and 1.0 -> 1.8V.")
    L("")
    L("In the behavioral classifier:")
    L("```spice")
    L("Score = sum(w * V(in)/1.8) + bias")
    L("```")
    L("")
    L("This correctly inverts the normalization: V(in)/1.8 recovers [0, 1].")
    L("")
    L("**The classifier IS correct for features in [0, 1.8V].**")
    L("**The problem is that actual features are NOT in [0, 1.8V].**")
    L("")

    L("## 5. The Calibration Gap")
    L("")
    L("### What the classifier expects:")
    L("- Feature 0 (BPF1 env): 0.0V (normal) to 1.8V (max fault)")
    L("- Feature 1 (BPF2 env): 0.0V (normal) to 1.8V (max fault)")
    L("- ... etc")
    L("")
    L("### What the analog chain produces:")
    L("- Feature 0 (BPF1 env): 0.9041V (normal) to 0.9044V (max fault)")
    L("- Feature 1 (BPF2 env): 0.9064V (normal) to 0.9088V (max fault)")
    L("- ... etc")
    L("")
    L("### The mapping required:")
    L("```")
    L("V_classifier = (V_analog - VCM) / (V_max_analog - VCM) * 1.8")
    L("```")
    L("For BPF3 envelope: (0.9097 - 0.9) / (0.9097 - 0.9032) * 1.8 = 26.8V")
    L("...which exceeds the supply. The analog range is simply too compressed.")
    L("")

    L("## 6. The Synthetic vs Real Data Issue")
    L("")
    L("The training uses synthetic data (when CWRU .mat files unavailable):")
    L("- `generate_synthetic_data()` creates signals with class-specific spectral profiles")
    L("- Each class dominated by one BPF band (identity matrix profiles)")
    L("- This creates LARGE, CLEAN spectral differences")
    L("")
    L("The full-chain stimulus also uses synthetic data:")
    L("- `generate_stimuli.py` creates bearing fault signals")
    L("- These model impulse excitation of resonances")
    L("- The spectral differences are SUBTLE (all faults excite similar resonance bands)")
    L("")
    L("**Mismatch**: Training data has each class strongly exciting one specific band.")
    L("Analog data has all fault classes exciting similar frequency ranges (2.5-3.5 kHz)")
    L("with subtle modulation differences that the envelope may not capture well.")
    L("")

    L("## 7. Re-Training Approach")
    L("")
    L("### Option A: Simulation-in-the-Loop Training")
    L("")
    L("1. Run analog simulations for many different input patterns")
    L("2. Extract actual envelope voltages from each simulation")
    L("3. Build a training dataset of (analog_features, labels)")
    L("4. Train classifier directly on analog feature space")
    L("5. Export weights for the millivolt-scale feature range")
    L("")
    L("Advantages: Perfectly matched to actual hardware")
    L("Disadvantages: Requires many SPICE simulations (slow)")
    L("")

    L("### Option B: Calibration Layer")
    L("")
    L("1. Keep existing training on [0,1] normalized features")
    L("2. Add a calibration step between envelope and classifier:")
    L("   `V_cal = (V_env - VCM_measured) * Gain_cal + VCM_output`")
    L("3. Gain_cal = 1.8 / (expected envelope range)")
    L("4. This is essentially a per-feature PGA after the envelope")
    L("")
    L("Advantages: Doesn't require retraining")
    L("Disadvantages: Requires per-channel gain stages (5 more amplifiers)")
    L("")

    L("### Option C: Rescale Classifier Weights (Recommended)")
    L("")
    L("1. Measure actual envelope range: [Vmin, Vmax] per channel")
    L("2. New normalization: feature_norm = (V - Vmin) / (Vmax - Vmin)")
    L("3. In SPICE: Score = sum(w' * (V(in) - Vmin) / (Vmax - Vmin)) + bias'")
    L("4. Weights stay the same, only the normalization changes")
    L("")
    L("For this to work:")
    L("```")
    L("Old: Score = sum(w * V/1.8) + bias")
    L("New: Score = sum(w * (V - Vmin)/(Vmax - Vmin)) + bias")
    L("")
    L("Expand: Score = sum(w/(Vmax-Vmin)) * V - sum(w*Vmin/(Vmax-Vmin)) + bias")
    L("      = sum(w_new * V) + bias_new")
    L("")
    L("Where: w_new = w / (Vmax - Vmin)")
    L("       bias_new = bias - sum(w * Vmin / (Vmax - Vmin))")
    L("```")
    L("")
    L("**But this requires that the analog features have the SAME relative")
    L("distribution as the training features, just linearly scaled.**")
    L("If the analog chain distorts the feature distribution (e.g., half-wave")
    L("vs full-wave rectification), the rescaling won't work.")
    L("")

    L("### Option D: End-to-End Retraining (Best Long-Term)")
    L("")
    L("1. Create a Python model of the analog chain:")
    L("   - PGA gain model (including clipping)")
    L("   - BPF transfer functions (actual Gm-C, not ideal Butterworth)")
    L("   - Half-wave rectifier model (not abs())")
    L("   - LPF with actual fc=92 Hz (not 10 Hz)")
    L("   - RMS squarer model")
    L("   - Peak detector model")
    L("2. Process training data through this analog model")
    L("3. Normalize the MODEL outputs (not ideal outputs)")
    L("4. Train classifier on model outputs")
    L("5. The weights will naturally account for analog non-idealities")
    L("")
    L("This is the most robust solution because it creates a digital twin")
    L("of the analog chain and trains against it.")
    L("")

    L("## 8. Specific Python vs Analog Mismatches to Fix")
    L("")
    L("| # | Mismatch | Impact | Fix |")
    L("|---|----------|--------|-----|")
    L("| 1 | BPF bands don't match (config vs actual) | HIGH | Retune BPFs or retrain |")
    L("| 2 | Full-wave vs half-wave rectifier | 2x DC output | Use full-wave or retrain |")
    L("| 3 | Envelope LPF 10 Hz vs 92 Hz | Different ripple | Align settings |")
    L("| 4 | Feature window 0.5s vs 0.2s | Averaging quality | Increase sim time |")
    L("| 5 | Kurtosis vs rms_ref constant | Wasted feature | Add kurtosis circuit |")
    L("| 6 | MinMax to [0,1.8V] vs actual [0.90,0.91V] | CRITICAL | Rescale or retrain |")
    L("| 7 | Synthetic training data vs synthetic stimuli | Distribution mismatch | Align generation |")
    L("")

    L("## 9. Priority Recommendation")
    L("")
    L("**Immediate (can fix without re-simulation):**")
    L("1. Rescale classifier weights for actual voltage range (Option C)")
    L("2. This requires measuring actual envelope ranges and updating")
    L("   the behavioral classifier SPICE model")
    L("")
    L("**Short-term (requires re-simulation):**")
    L("3. Increase V_SCALE to 0.1-0.2 V/g")
    L("4. Fix BPF bias voltages for channels 4-5")
    L("5. Increase sim duration to 500ms")
    L("")
    L("**Medium-term (requires retraining):**")
    L("6. Build analog chain Python model (Option D)")
    L("7. Retrain with analog-aware features")
    L("8. Add real CWRU data to training pipeline")

    with open(REPORT, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Expert 10 report written to {REPORT}")

if __name__ == '__main__':
    main()
