#!/usr/bin/env python3
"""Expert 7: Envelope Detector Architecture Analysis"""

import os
import numpy as np

REPORT = os.path.join(os.path.dirname(__file__), 'expert_07_envelope_architecture.md')
VIBROSENSE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def main():
    lines = []
    L = lines.append

    L("# Expert Report 07: Envelope Detector Architecture Analysis")
    L("")
    L("## 1. Current Architecture (envelope_det_fixed.spice)")
    L("")
    L("### Block Diagram")
    L("```")
    L("vin --+--[OTA1]--[PMOS1]--+-- rect --[Gm-C LPF]-- vout")
    L("      |                    |")
    L("vcm --+--[OTA2]--[PMOS2]--+")
    L("                           |")
    L("                    [NMOS discharge]")
    L("                           |")
    L("                          vcm")
    L("```")
    L("")

    L("### Stage 1: Precision Half-Wave Rectifier")
    L("")
    L("**OTA1** (ota_pga_v2): Two-stage Miller compensated OTA")
    L("- inp = vin, inn = rect (negative feedback)")
    L("- When vin > rect: OTA1 output goes low, turns on PMOS1, rect charges up toward vin")
    L("- When vin < rect: OTA1 output goes high, PMOS1 turns off")
    L("")
    L("**OTA2** (ota_pga_v2): Same topology")
    L("- inp = vcm, inn = rect")
    L("- When rect > vcm: OTA2 output goes low, turns on PMOS2, clamps rect toward vcm")
    L("- When rect < vcm: OTA2 output goes high, PMOS2 turns off")
    L("")
    L("**PMOS output transistors**: W=2u L=1u each")
    L("- These are the charge-up devices")
    L("- Ron ~ 1/(mu_p * Cox * W/L * Vov) ~ several kOhm")
    L("")
    L("**NMOS discharge**: W=0.42u L=100u, gate=VDD, source=vcm")
    L("- Operating in deep triode (Vgs=0.9V, Vth~0.5V, Vov=0.4V)")
    L("- Effective R ~ 6.85 MOhm (from design comments)")
    L("- At Vds=10mV: I = 10mV/6.85M = 1.46 nA")
    L("- tau with ~1pF parasitic = 6.85us")
    L("")

    L("### Stage 2: Gm-C Low-Pass Filter")
    L("")
    L("**5T OTA** with 5nF cap:")
    L("- Diff pair: W=2u L=4u NFET")
    L("- Tail: W=1u L=8u NFET, biased at vbn_lpf=0.70V")
    L("- PMOS mirror: W=4u L=4u")
    L("")

    # Estimate gm
    L("**gm estimation:**")
    L("- vbn_lpf = 0.70V, tail W/L = 1/8")
    L("- SKY130 NFET Vth ~ 0.5V, Vov = 0.70 - 0.5 = 0.2V")
    L("- In saturation: Id_tail ~ (1/2) * mu_n * Cox * (W/L) * Vov^2")
    L("- mu_n*Cox for SKY130 ~ 270 uA/V^2")
    L("- Id_tail ~ 0.5 * 270e-6 * (1/8) * 0.04 = 675 nA")
    L("- Each side: Id = 337 nA")
    L("- gm = 2*Id/Vov = 2*337n/0.2 = 3.37 uS (if in strong inversion)")
    L("- gm = Id/nVt = 337n/(1.3*26m) = 10 uS (if in weak inversion)")
    L("- Likely moderate inversion: gm ~ 2-5 uS")
    L("")
    L("**Cutoff frequency:**")
    L("- fc = gm / (2*pi*C) = 3 uS / (2*pi*5nF) = 95 Hz")
    L("- This matches the design target of ~92 Hz")
    L("")
    L("**Settling time:**")
    L("- tau = C/gm = 5nF/3uS = 1.67 ms")
    L("- 5*tau = 8.3 ms (to 99% of final value)")
    L("- With 200ms simulation, the LPF has >20 time constants to settle")
    L("")

    L("## 2. Rectification Efficiency Analysis")
    L("")
    L("For a sine wave input at amplitude A above VCM:")
    L("- Ideal half-wave rectifier: DC = A/pi = 0.318*A")
    L("- With OTA feedback: approaches ideal for A >> dead zone")
    L("")
    L("Dead zone of OTA-based rectifier:")
    L("- OTA gain ~ 75 dB = 5623 V/V")
    L("- Minimum detectable signal: Vdd/gain = 1.8/5623 = 0.32 mV")
    L("- For 10 mVpp sine (5mV amplitude): well above dead zone")
    L("")
    L("**Estimated conversion:**")
    L("- Input: 50 mVpp sine on top of VCM -> Amplitude = 25 mV")
    L("- Rectified peak: ~25 mV above VCM")
    L("- After LPF averaging: ~25/pi = 8 mV above VCM")
    L("- This matches the observed ~4-10 mV offsets in the full-chain!")
    L("")

    L("## 3. Performance Issues")
    L("")
    L("### Issue 1: Low Rectification Output for Small Signals")
    L("")
    L("The rectifier works correctly but the OUTPUT RANGE is limited by physics:")
    L("- A half-wave rectifier's DC output is always less than the peak input")
    L("- For 10 mVpp BPF output: DC envelope = ~3 mV")
    L("- For 50 mVpp BPF output: DC envelope = ~16 mV")
    L("- For 100 mVpp BPF output: DC envelope = ~32 mV")
    L("")
    L("To get 500 mV DC envelope (needed for good classifier spread),")
    L("we'd need ~1.6 Vpp at the BPF output -- which uses most of the rail.")
    L("")

    L("### Issue 2: NMOS Discharge vs Signal Current")
    L("")
    L("The NMOS discharge transistor provides ~1.5 nA per mV above VCM.")
    L("The OTA output current through PMOS: gm * Vdiff")
    L("- OTA gm ~ 30 uS, for 10 mV input: I_ota = 300 nA >> 1.5 nA")
    L("- The discharge doesn't compete with charge-up")
    L("- But between pulses, the discharge slowly pulls rect back to VCM")
    L("- tau_discharge = 6.85 MOhm * ~1 pF = 6.85 us")
    L("- At BPF3 freq (3162 Hz), period = 316 us >> tau")
    L("- So rect fully discharges between positive half-cycles")
    L("- This is correct half-wave rectifier behavior")
    L("")

    L("### Issue 3: Competition Between OTA1 and OTA2")
    L("")
    L("When vin ~ VCM (zero crossing), both OTAs are active simultaneously.")
    L("OTA1 tries to follow vin, OTA2 tries to clamp to vcm.")
    L("The PMOS transistors act as pass devices, so the lower OTA output")
    L("(more negative gate) wins (turns PMOS harder).")
    L("")
    L("This is the correct behavior: at vin > vcm, OTA1 pulls rect up;")
    L("at vin < vcm, OTA2 clamps rect at vcm. The crossover is smooth")
    L("due to the high OTA gain.")
    L("")

    L("## 4. Comparison with Block 04 Behavioral Model")
    L("")
    L("The original Block 04 `design.cir` uses a behavioral model:")
    L("- B_hw1: I = max(0, 2.5e-6 * (vin - vcm))")
    L("- B_hw2: I = max(0, 2.5e-6 * (vcm - vin))")
    L("- R_rect = 400k -> V(rect) = |vin - vcm| (full-wave)")
    L("- G_lpf: gm = 6.28 nS, C = 10 pF -> fc = 100 Hz")
    L("")
    L("**The full-chain uses a DIFFERENT envelope detector** (envelope_det_fixed.spice)")
    L("which is transistor-level with a HALF-wave rectifier, not full-wave.")
    L("")
    L("| Feature | Behavioral (design.cir) | Transistor-level (fixed) |")
    L("|---------|------------------------|-------------------------|")
    L("| Rectification | Full-wave | Half-wave |")
    L("| Dead zone | 0 (ideal) | ~0.3 mV |")
    L("| DC output | (2/pi)*A = 0.637*A | (1/pi)*A = 0.318*A |")
    L("| LPF cutoff | 100 Hz | ~92 Hz |")
    L("| LPF settling | ~8 ms | ~8 ms |")
    L("")
    L("**The transistor-level half-wave rectifier produces HALF the DC output")
    L("compared to the behavioral full-wave model.** This is another factor")
    L("contributing to the small envelope values.")
    L("")

    L("## 5. Architectural Improvements")
    L("")
    L("### Improvement 1: Full-Wave Rectification")
    L("Add a second OTA pair that handles the negative half-cycle:")
    L("- OTA3: inp=vcm, inn=vin (inverts the input)")
    L("- OTA4: same clamp function")
    L("- Sum the outputs")
    L("- **Effect**: 2x DC output")
    L("")

    L("### Improvement 2: Post-Envelope Gain Stage")
    L("Add an amplifier after the LPF:")
    L("- Differential: amplify (Venv - VCM)")
    L("- Gain = 50-100x")
    L("- Output: VCM + 50*(Venv - VCM)")
    L("- 5 mV envelope -> 250 mV signal")
    L("- Can use same capacitive-feedback PGA topology")
    L("- **Effect**: Directly maps millivolt features to hundreds of millivolts")
    L("")

    L("### Improvement 3: Chopper-Stabilized Rectifier")
    L("For ultra-low-signal applications:")
    L("- Chop the BPF output to baseband")
    L("- Amplify at baseband (avoid 1/f noise)")
    L("- Low-pass filter")
    L("- Higher complexity but much better for sub-millivolt signals")
    L("")

    L("### Improvement 4: Peak-and-Hold Instead of Average")
    L("Replace LPF with peak detector (like the RMS block's peak_detector):")
    L("- Captures the PEAK of the rectified signal, not the average")
    L("- For impulsive signals (bearing faults), peak >> average")
    L("- Would produce 3-10x larger feature values")
    L("- Tradeoff: more sensitive to noise spikes")
    L("")

    L("## 6. Recommended Priority")
    L("")
    L("1. **Post-envelope gain** (simplest, most impactful): Add 50x gain after LPF")
    L("2. **Full-wave rectification**: Convert from half-wave to full-wave (2x improvement)")
    L("3. **Retrain classifier**: Adapt weights to actual voltage range (software-only fix)")
    L("4. **Peak-and-hold**: Consider for v2 if averaging doesn't suffice")

    with open(REPORT, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Expert 07 report written to {REPORT}")

if __name__ == '__main__':
    main()
