#!/usr/bin/env python3
"""Expert 6: Bearing Fault Frequency Analysis (Domain Knowledge)"""

import os
import json
import numpy as np

REPORT = os.path.join(os.path.dirname(__file__), 'expert_06_bearing_frequencies.md')
VIBROSENSE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def main():
    lines = []
    L = lines.append

    L("# Expert Report 06: Bearing Fault Frequency and Domain Analysis")
    L("")
    L("## 1. Bearing Defect Frequency Theory")
    L("")
    L("For a rolling element bearing, defect frequencies are:")
    L("")
    L("- **BPFO** (Ball Pass Frequency, Outer race) = (n/2) * f_s * (1 - d/D * cos(alpha))")
    L("- **BPFI** (Ball Pass Frequency, Inner race) = (n/2) * f_s * (1 + d/D * cos(alpha))")
    L("- **BSF** (Ball Spin Frequency) = (D/(2*d)) * f_s * (1 - (d/D)^2 * cos^2(alpha))")
    L("- **FTF** (Fundamental Train/Cage Frequency) = (f_s/2) * (1 - d/D * cos(alpha))")
    L("")
    L("Where:")
    L("- n = number of rolling elements")
    L("- f_s = shaft frequency")
    L("- d = ball diameter")
    L("- D = pitch diameter")
    L("- alpha = contact angle")
    L("")

    L("## 2. CWRU Test Bearing Parameters (6205-2RS)")
    L("")
    L("| Parameter | Value |")
    L("|-----------|-------|")
    L("| Balls (n) | 9 |")
    L("| Ball diameter (d) | 7.94 mm |")
    L("| Pitch diameter (D) | 39.04 mm |")
    L("| Contact angle (alpha) | 0 degrees |")
    L("| d/D | 0.2034 |")
    L("")

    # Calculate exact frequencies
    n_balls = 9
    d_D = 7.94 / 39.04  # 0.2034
    alpha = 0  # radians
    cos_a = np.cos(alpha)

    rpms = [1797, 1772, 1750, 1730]

    L("## 3. Fault Frequencies at Different Shaft Speeds")
    L("")
    L("| RPM  | f_shaft | BPFO (Hz) | BPFI (Hz) | BSF (Hz)  | FTF (Hz)  |")
    L("|------|---------|-----------|-----------|-----------|-----------|")
    for rpm in rpms:
        f_s = rpm / 60.0
        bpfo = (n_balls / 2) * f_s * (1 - d_D * cos_a)
        bpfi = (n_balls / 2) * f_s * (1 + d_D * cos_a)
        bsf = (1 / (2 * d_D)) * f_s * (1 - d_D**2 * cos_a**2)
        ftf = (f_s / 2) * (1 - d_D * cos_a)
        L(f"| {rpm} | {f_s:.1f} Hz | {bpfo:.1f} | {bpfi:.1f} | {bsf:.1f} | {ftf:.1f} |")
    L("")

    f_s = 1797 / 60.0
    bpfo = (n_balls / 2) * f_s * (1 - d_D * cos_a)
    bpfi = (n_balls / 2) * f_s * (1 + d_D * cos_a)
    bsf = (1 / (2 * d_D)) * f_s * (1 - d_D**2 * cos_a**2)

    L("At 1797 RPM (the CWRU standard):")
    L(f"- BPFO = {bpfo:.1f} Hz")
    L(f"- BPFI = {bpfi:.1f} Hz")
    L(f"- BSF = {bsf:.1f} Hz")
    L("")

    L("## 4. Stimulus Script Values vs Correct Values")
    L("")
    L("From `generate_stimuli.py`:")
    L("- BPFI = 5.415 * f_shaft = 162.2 Hz")
    L("- BPFO = 3.585 * f_shaft = 107.4 Hz")
    L("- BSF = 2.357 * f_shaft = 70.6 Hz")
    L("")
    L("Correct values:")
    L(f"- BPFI = {bpfi:.1f} Hz  (script: 162.2 Hz) -- {'MATCH' if abs(bpfi - 162.2) < 1 else 'MISMATCH'}")
    L(f"- BPFO = {bpfo:.1f} Hz  (script: 107.4 Hz) -- {'MATCH' if abs(bpfo - 107.4) < 1 else 'MISMATCH'}")
    L(f"- BSF = {bsf:.1f} Hz   (script: 70.6 Hz) -- {'MATCH' if abs(bsf - 70.6) < 2 else 'MISMATCH'}")
    L("")
    L("**The fundamental frequencies in the script are approximately correct.**")
    L("")

    L("## 5. How Bearing Faults Actually Manifest in Vibration")
    L("")
    L("Bearing fault frequencies (100-162 Hz) are NOT directly visible in the")
    L("vibration spectrum as pure tones. Instead:")
    L("")
    L("1. **Impact mechanism**: Each time a defect passes through the loaded zone,")
    L("   it produces a short impulse that excites the bearing's structural resonance")
    L("   (typically 2-10 kHz).")
    L("")
    L("2. **The vibration signal**: Carrier = high-frequency resonance (kHz)")
    L("   modulated at the fault frequency (Hz). This is AM modulation.")
    L("")
    L("3. **Envelope analysis principle**: The BPF isolates the resonance band,")
    L("   the envelope detector demodulates the AM, and the resulting signal")
    L("   shows the fault frequency. Different fault types excite different")
    L("   resonances with different modulation patterns.")
    L("")
    L("4. **Key distinction between fault types**:")
    L("   - Inner race: AM modulated by shaft frequency (because inner race rotates)")
    L("   - Outer race: NO amplitude modulation (stationary race)")
    L("   - Ball fault: Intermittent contact, 2x BSF repetition rate")
    L("   - Normal: Random broadband, no periodic components")
    L("")

    L("## 6. Synthetic Stimulus Realism Assessment")
    L("")
    L("The synthetic stimuli in `generate_stimuli.py` model:")
    L("")
    L("| Feature | Synthetic | Real CWRU | Realistic? |")
    L("|---------|-----------|-----------|------------|")
    L("| Impulse repetition | Correct | Correct | YES |")
    L("| Resonance frequency | 2.5-3.5 kHz | 2-6 kHz | YES |")
    L("| Impulse decay | exp(-600 to -800) | varies | FAIR |")
    L("| AM for inner race | cos(f_shaft) | cos(f_shaft) | YES |")
    L("| No AM for outer | Yes | Yes | YES |")
    L("| Ball intermittent | abs(sin(BSF)) | random | FAIR |")
    L("| Noise floor | Gaussian | Colored | FAIR |")
    L("| Duration | 200 ms | 10+ seconds | **SHORT** |")
    L("| Number of impulses | ~20-30 | ~1000+ | **LOW** |")
    L("")
    L("### Biggest Issue: 200 ms Duration")
    L("")
    L("At BPFI = 162.2 Hz, one period = 6.2 ms. In 200 ms, there are ~32 impulses.")
    L("This is barely enough for envelope detection to produce a stable DC.")
    L("Real CWRU recordings are 10+ seconds (>1600 impulses).")
    L("")
    L("At BPFO = 107.4 Hz, one period = 9.3 ms. In 200 ms, ~21 impulses.")
    L("At 2*BSF = 141.2 Hz, one period = 7.1 ms. In 200 ms, ~28 impulses.")
    L("")
    L("The envelope LPF has fc=92 Hz, settling time ~8.7 ms. With 200 ms sim,")
    L("the envelope has time to settle, but the STATISTICAL quality of the")
    L("envelope is poor with so few impulses.")
    L("")

    L("## 7. Do Fault Frequencies Fall Within BPF Bands?")
    L("")
    L("The FUNDAMENTAL fault frequencies (70-162 Hz) are in BPF1's range (100-500 Hz).")
    L("But that's the wrong question. What matters is:")
    L("- Which BPF band captures the RESONANCE excited by each fault type?")
    L("")
    L("Synthetic stimulus resonances:")
    L("- Inner race: 3000 Hz resonance -> BPF3 (3162 Hz center) -- **GOOD MATCH**")
    L("- Outer race: 2500 Hz resonance -> BPF2/BPF3 boundary -- **FAIR**")
    L("- Ball fault: 3500 Hz resonance -> BPF3/BPF4 boundary -- **FAIR**")
    L("")
    L("**Problem**: The resonances are clustered around 2500-3500 Hz, which is")
    L("BPF3's passband. This means BPF3 will respond to ALL fault types,")
    L("and the discrimination relies on subtle amplitude differences between")
    L("BPF2 (1001 Hz) and BPF4 (7236 Hz) sidebands. With the current signal")
    L("levels, these sideband differences are in the noise.")
    L("")

    L("## 8. Recommendations")
    L("")
    L("1. **Spread resonance frequencies**: Each fault type should excite a DIFFERENT")
    L("   resonance band. This could be done by adjusting the synthetic impulse")
    L("   response frequencies (e.g., inner=2 kHz, outer=3.5 kHz, ball=5 kHz)")
    L("   or by using real CWRU data which naturally has this separation.")
    L("")
    L("2. **Increase simulation duration** to at least 500 ms for better envelope")
    L("   statistics (more impulse averaging).")
    L("")
    L("3. **Increase fault amplitude**: fault_amplitude=3.0 with V_SCALE=0.02 gives")
    L("   only 60 mV peak stimulus. Real accelerometers produce 0.5-5V peak for")
    L("   damaged bearings. Increase V_SCALE to at least 0.1 V/g.")
    L("")
    L("4. **Consider using actual CWRU .mat files** instead of synthetic data.")
    L("   The download script exists (`download_cwru.py`) but wasn't used.")

    with open(REPORT, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Expert 06 report written to {REPORT}")

if __name__ == '__main__':
    main()
