#!/usr/bin/env python3
"""plot_all.py — Generate all required plots for Block 02: Feedback Network.

Reads CSV data files generated by generate_plot_data.py and MC simulation.
Produces PNG plots for README.md.
"""

import os
import csv
import numpy as np

os.chdir(os.path.dirname(os.path.abspath(__file__)))

# Check if matplotlib is available
try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    HAS_MPL = True
except ImportError:
    HAS_MPL = False
    print("WARNING: matplotlib not available. Generating text summaries instead.")

TARGET_VFB = 1.226  # V

# --- Helper ---
def read_csv(path):
    with open(path) as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    return rows

# --- 1. VFB vs Temperature ---
def plot_vfb_vs_temp():
    if not os.path.exists('plot_temp_data.csv'):
        print("  SKIP: plot_temp_data.csv not found")
        return
    rows = read_csv('plot_temp_data.csv')
    temps = [float(r['temperature_C']) for r in rows]
    vfbs = [float(r['vfb_V']) for r in rows]

    if not HAS_MPL:
        print(f"  Temp range: {min(temps)} to {max(temps)} C")
        print(f"  VFB range: {min(vfbs)*1000:.2f} to {max(vfbs)*1000:.2f} mV")
        return

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(temps, [v * 1000 for v in vfbs], 'b-o', markersize=3, linewidth=1.5)
    ax.axhline(y=TARGET_VFB * 1000, color='r', linestyle='--', label=f'Target = {TARGET_VFB*1000:.1f} mV')
    ax.axhspan((TARGET_VFB - 0.001) * 1000, (TARGET_VFB + 0.001) * 1000,
               alpha=0.2, color='green', label='±1 mV spec band')
    ax.set_xlabel('Temperature (°C)', fontsize=12)
    ax.set_ylabel('VFB (mV)', fontsize=12)
    ax.set_title('Feedback Voltage vs Temperature\nsky130_fd_pr__res_xhigh_po, w=2.0 µm', fontsize=13)
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3)
    drift = (max(vfbs) - min(vfbs)) * 1000
    ax.annotate(f'Total drift: {drift:.2f} mV', xy=(0.02, 0.02),
                xycoords='axes fraction', fontsize=10,
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    plt.tight_layout()
    plt.savefig('vfb_vs_temp.png', dpi=150)
    plt.close()
    print("  Saved vfb_vs_temp.png")

# --- 2. VFB at PVT Corners (bar chart) ---
def plot_vfb_corners():
    if not os.path.exists('plot_corners_data.csv'):
        print("  SKIP: plot_corners_data.csv not found")
        return
    rows = read_csv('plot_corners_data.csv')

    if not HAS_MPL:
        for r in rows:
            print(f"  {r['corner']} {r['temperature_C']}C: VFB = {float(r['vfb_V'])*1000:.2f} mV")
        return

    # Group by (corner, temp)
    labels = []
    values = []
    for r in rows:
        labels.append(f"{r['corner']}\n{r['temperature_C']}°C")
        values.append(float(r['vfb_V']) * 1000)

    fig, ax = plt.subplots(figsize=(12, 5))
    colors = []
    for r in rows:
        c = r['corner']
        if c == 'TT':
            colors.append('#4CAF50')
        elif c == 'SS':
            colors.append('#2196F3')
        elif c == 'FF':
            colors.append('#F44336')
        elif c == 'SF':
            colors.append('#FF9800')
        else:
            colors.append('#9C27B0')

    bars = ax.bar(range(len(labels)), values, color=colors, alpha=0.8, edgecolor='black', linewidth=0.5)
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, fontsize=8)

    # Spec band
    ax.axhline(y=TARGET_VFB * 1000, color='red', linestyle='--', linewidth=1.5, label='Target')
    ax.axhspan((TARGET_VFB - 0.005) * 1000, (TARGET_VFB + 0.005) * 1000,
               alpha=0.15, color='red', label='±5 mV spec')

    ax.set_ylabel('VFB (mV)', fontsize=12)
    ax.set_title('VFB at All PVT Corners\n5 corners × 3 temperatures', fontsize=13)
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3, axis='y')
    plt.tight_layout()
    plt.savefig('vfb_corners.png', dpi=150)
    plt.close()
    print("  Saved vfb_corners.png")

# --- 3. MC Histogram ---
def plot_mc_histogram():
    if not os.path.exists('mc_vfb_data.txt'):
        print("  SKIP: mc_vfb_data.txt not found")
        return

    mc_vals = []
    with open('mc_vfb_data.txt') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 2:
                try:
                    mc_vals.append(float(parts[1]))
                except ValueError:
                    pass

    if len(mc_vals) < 10:
        print(f"  SKIP: only {len(mc_vals)} MC samples")
        return

    mc_arr = np.array(mc_vals)
    mean_v = np.mean(mc_arr)
    std_v = np.std(mc_arr)

    if not HAS_MPL:
        print(f"  MC: mean={mean_v*1000:.2f} mV, std={std_v*1000:.2f} mV, 3σ={3*std_v*1000:.2f} mV")
        return

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(mc_arr * 1000, bins=30, color='steelblue', edgecolor='black', alpha=0.7, linewidth=0.5)
    ax.axvline(x=mean_v * 1000, color='red', linestyle='-', linewidth=2, label=f'Mean = {mean_v*1000:.2f} mV')
    ax.axvline(x=(mean_v - std_v) * 1000, color='orange', linestyle='--', linewidth=1.5, label=f'±1σ = {std_v*1000:.2f} mV')
    ax.axvline(x=(mean_v + std_v) * 1000, color='orange', linestyle='--', linewidth=1.5)
    ax.axvline(x=(mean_v - 3*std_v) * 1000, color='darkred', linestyle=':', linewidth=1.5, label=f'±3σ = {3*std_v*1000:.2f} mV')
    ax.axvline(x=(mean_v + 3*std_v) * 1000, color='darkred', linestyle=':', linewidth=1.5)
    ax.axvline(x=TARGET_VFB * 1000, color='green', linestyle='--', linewidth=1, label=f'Target = {TARGET_VFB*1000:.1f} mV')
    ax.set_xlabel('VFB (mV)', fontsize=12)
    ax.set_ylabel('Count', fontsize=12)
    ax.set_title(f'Monte Carlo Mismatch: VFB Distribution ({len(mc_vals)} runs)', fontsize=13)
    ax.legend(loc='upper right', fontsize=9)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig('mc_vfb_histogram.png', dpi=150)
    plt.close()
    print("  Saved mc_vfb_histogram.png")

# --- 4. Noise spectral density (analytical) ---
def plot_noise():
    """Plot analytical noise spectral density for the resistor divider."""
    if not HAS_MPL:
        print("  SKIP: matplotlib not available")
        return

    # Measured values from simulation
    R_TOP = 316050  # ohm (approximate from sim)
    R_BOT = 102800  # ohm
    R_par = R_TOP * R_BOT / (R_TOP + R_BOT)
    k = 1.3806e-23
    T = 300  # K

    freqs = np.logspace(0, 6, 500)  # 1 Hz to 1 MHz
    # Thermal noise is white (flat spectrum)
    noise_density = np.sqrt(4 * k * T * R_par) * np.ones_like(freqs)  # V/sqrt(Hz)
    noise_nv = noise_density * 1e9  # nV/sqrt(Hz)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.semilogx(freqs, noise_nv, 'b-', linewidth=2)
    ax.axhline(y=50e-6 * 1e9 / np.sqrt(1e6), color='r', linestyle='--', alpha=0.5)
    ax.set_xlabel('Frequency (Hz)', fontsize=12)
    ax.set_ylabel('Noise Spectral Density (nV/√Hz)', fontsize=12)
    ax.set_title(f'Thermal Noise at VFB Node\nR_parallel = {R_par/1000:.1f} kΩ', fontsize=13)
    ax.grid(True, alpha=0.3, which='both')
    rms_uv = np.sqrt(4 * k * T * R_par * 1e6) * 1e6
    ax.annotate(f'Flat @ {noise_nv[0]:.1f} nV/√Hz\nIntegrated (1Hz–1MHz): {rms_uv:.1f} µVrms',
                xy=(0.6, 0.85), xycoords='axes fraction', fontsize=10,
                bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))
    plt.tight_layout()
    plt.savefig('noise_vfb.png', dpi=150)
    plt.close()
    print("  Saved noise_vfb.png")

if __name__ == '__main__':
    print("=== Generating plots for Block 02 ===")
    plot_vfb_vs_temp()
    plot_vfb_corners()
    plot_mc_histogram()
    plot_noise()
    print("Done.")
