#!/usr/bin/env python3
"""Generate the full 8-input × 4-bit MAC SPICE netlist.
Also generates testbenches for Priority 1-3 verification.
Includes bottom-plate parasitic caps to model real MIM behavior (Priority 2).
"""

import os

WORK_DIR = os.path.dirname(os.path.abspath(__file__))
N_INPUTS = 8
N_BITS = 4
CUNIT = 50  # fF
# MIM bottom-plate parasitic: ~10% of cap value
BP_PARASITIC_FRAC = 0.10


def gen_mac_8in4b():
    """Generate mac_8in4b.spice — full 8-input, 4-bit weight MAC unit."""
    lines = []
    lines.append("* VibroSense Block 06: Full MAC Unit — 8 inputs × 4-bit weights")
    lines.append("* Process: SKY130A | Supply: 1.8V")
    lines.append("* Generated by gen_mac_8in4b.py")
    lines.append("* Bottom-plate parasitic caps included (10% of MIM cap value)")
    lines.append("*")
    lines.append(f"* Cunit = {CUNIT} fF | Bits: {', '.join(f'{2**b}×Cunit={2**b*CUNIT}fF' for b in range(N_BITS))}")
    lines.append(f"* Max weight per input = {2**N_BITS - 1} → {(2**N_BITS-1)*CUNIT} fF")
    lines.append(f"* Total cap (all max): {N_INPUTS * (2**N_BITS - 1) * CUNIT} fF + parasitic")
    lines.append("")

    # Build port list
    ports = ["bl", "vss", "vdd"]
    for i in range(N_INPUTS):
        ports.append(f"in{i}")
    ports += ["phi_e", "phi_eb", "phi_r"]
    for i in range(N_INPUTS):
        for b in range(N_BITS):
            ports.append(f"en{i}b{b}")
            ports.append(f"en{i}b{b}b")

    # Wrap ports at 8 per line
    port_lines = [".subckt mac_8in4b"]
    chunk = []
    for p in ports:
        chunk.append(p)
        if len(chunk) >= 8:
            port_lines.append("+ " + " ".join(chunk))
            chunk = []
    if chunk:
        port_lines.append("+ " + " ".join(chunk))
    lines.extend(port_lines)

    lines.append("")
    lines.append(f".param cunit = {CUNIT}f")
    lines.append("")

    # Generate per-input, per-bit structures
    for i in range(N_INPUTS):
        for b in range(N_BITS):
            scale = 2**b
            cap_fF = scale * CUNIT
            bp_fF = cap_fF * BP_PARASITIC_FRAC
            top = f"top{i}b{b}"
            en = f"en{i}b{b}"
            enb = f"en{i}b{b}b"

            lines.append(f"* --- INPUT {i}, BIT {b} ({scale}×Cunit = {cap_fF}fF) ---")
            # Sample TG
            lines.append(f"XNt{i}b{b} in{i} {en} {top} vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
            lines.append(f"XPt{i}b{b} in{i} {enb} {top} vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
            # Weight cap (top plate to ground) + bottom-plate parasitic
            lines.append(f"C{i}b{b} {top} vss {{{scale}*cunit}}")
            if bp_fF > 0:
                lines.append(f"Cbp{i}b{b} {top} vss {bp_fF}f")
            # Eval TG
            lines.append(f"XNe{i}b{b} {top} phi_e bl vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
            lines.append(f"XPe{i}b{b} {top} phi_eb bl vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
            # Reset switch
            lines.append(f"XNr{i}b{b} {top} phi_r vss vss sky130_fd_pr__nfet_01v8 W=0.42u L=0.15u")
            lines.append("")

    # Bitline reset + parasitic
    lines.append("* --- Bitline reset + routing parasitic ---")
    lines.append("XNblrst bl phi_r vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("Cpar bl vss 80f")
    lines.append("")
    lines.append(".ends mac_8in4b")

    path = os.path.join(WORK_DIR, "mac_8in4b.spice")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Generated {path}")

    # Count devices
    n_tg = N_INPUTS * N_BITS * 2  # NMOS+PMOS per sample TG
    n_eval_tg = N_INPUTS * N_BITS * 2  # NMOS+PMOS per eval TG
    n_reset = N_INPUTS * N_BITS  # one NMOS per cap reset
    n_bl_reset = 1
    total = n_tg + n_eval_tg + n_reset + n_bl_reset
    print(f"  Transistors: {total} ({n_tg} sample TG + {n_eval_tg} eval TG + {n_reset} cap reset + {n_bl_reset} BL reset)")
    n_caps = N_INPUTS * N_BITS  # weight caps
    n_bp = N_INPUTS * N_BITS  # parasitic caps
    total_cap_fF = sum(2**b * CUNIT for b in range(N_BITS)) * N_INPUTS
    total_bp_fF = total_cap_fF * BP_PARASITIC_FRAC
    print(f"  Caps: {n_caps} weight + {n_bp} parasitic + 1 BL parasitic")
    print(f"  Total weight cap: {total_cap_fF} fF = {total_cap_fF/1000:.1f} pF")
    print(f"  Total bottom-plate parasitic: {total_bp_fF:.0f} fF")
    print(f"  Bitline total: {total_cap_fF + total_bp_fF + 80:.0f} fF")
    return total


def gen_tb_linearity_8in4b():
    """Generate testbench: sweep one input with max weight (15), verify linearity."""
    lines = []
    lines.append("* TB: 8in4b MAC Linearity — sweep in0 with weight=15, all others off")
    lines.append('.lib "sky130_minimal.lib.spice" tt')
    lines.append('.include "mac_8in4b.spice"')
    lines.append("")
    lines.append("Vdd vdd 0 dc 1.8")
    lines.append("Vss vss 0 dc 0")
    lines.append("")
    lines.append("* Sweep voltage on input 0 (parametric)")
    lines.append(".param vin_val = 0.9")
    lines.append("Vin0 in0 0 dc {vin_val}")
    for i in range(1, N_INPUTS):
        lines.append(f"Vin{i} in{i} 0 dc 0")
    lines.append("")

    # Clock phases
    lines.append("Vphi_e phi_e 0 pulse(0 1.8 220n 2n 2n 100n 500n)")
    lines.append("Vphi_eb phi_eb 0 pulse(1.8 0 220n 2n 2n 100n 500n)")
    lines.append("Vphi_r phi_r 0 pulse(0 1.8 340n 2n 2n 100n 500n)")
    lines.append("")

    # Enable signals: input 0 all bits ON, all others OFF
    for i in range(N_INPUTS):
        for b in range(N_BITS):
            if i == 0:
                lines.append(f"Ven{i}b{b}  en{i}b{b}  0 pulse(0 1.8 10n 2n 2n 190n 500n)")
                lines.append(f"Ven{i}b{b}b en{i}b{b}b 0 pulse(1.8 0 10n 2n 2n 190n 500n)")
            else:
                lines.append(f"Ven{i}b{b}  en{i}b{b}  0 dc 0")
                lines.append(f"Ven{i}b{b}b en{i}b{b}b 0 dc 1.8")
    lines.append("")

    # Instantiate MAC
    inst_ports = ["bl", "vss", "vdd"]
    for i in range(N_INPUTS):
        inst_ports.append(f"in{i}")
    inst_ports += ["phi_e", "phi_eb", "phi_r"]
    for i in range(N_INPUTS):
        for b in range(N_BITS):
            inst_ports.append(f"en{i}b{b}")
            inst_ports.append(f"en{i}b{b}b")

    inst_lines = ["XMAC"]
    chunk = []
    for p in inst_ports:
        chunk.append(p)
        if len(chunk) >= 10:
            inst_lines.append("+ " + " ".join(chunk))
            chunk = []
    if chunk:
        inst_lines.append("+ " + " ".join(chunk))
    inst_lines.append("+ mac_8in4b")
    lines.extend(inst_lines)

    lines.append("")
    lines.append(".control")
    lines.append("tran 0.5n 1.5u uic")
    lines.append("meas tran vbl FIND v(bl) AT=780n")
    lines.append('echo "RESULT: vbl = $&vbl"')
    lines.append("quit")
    lines.append(".endc")
    lines.append(".end")

    path = os.path.join(WORK_DIR, "tb_8in4b_linearity.spice")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Generated {path}")


def gen_tb_multiinput():
    """Generate testbench: all 8 inputs with different voltages and weights."""
    # Test case: varied inputs and weights
    test_inputs = [0.9, 0.45, 1.35, 0.6, 1.1, 0.3, 0.75, 1.5]  # Voltages
    test_weights = [15, 8, 12, 3, 10, 5, 7, 1]  # 4-bit codes (0-15)

    lines = []
    lines.append("* TB: 8in4b Multi-Input MAC — all inputs active with diverse weights")
    lines.append('.lib "sky130_minimal.lib.spice" tt')
    lines.append('.include "mac_8in4b.spice"')
    lines.append("")
    lines.append("Vdd vdd 0 dc 1.8")
    lines.append("Vss vss 0 dc 0")
    lines.append("")
    for i in range(N_INPUTS):
        lines.append(f"Vin{i} in{i} 0 dc {test_inputs[i]}")
    lines.append("")

    lines.append("Vphi_e phi_e 0 pulse(0 1.8 220n 2n 2n 100n 500n)")
    lines.append("Vphi_eb phi_eb 0 pulse(1.8 0 220n 2n 2n 100n 500n)")
    lines.append("Vphi_r phi_r 0 pulse(0 1.8 340n 2n 2n 100n 500n)")
    lines.append("")

    for i in range(N_INPUTS):
        w = test_weights[i]
        for b in range(N_BITS):
            bit_on = bool(w & (1 << b))
            if bit_on:
                lines.append(f"Ven{i}b{b}  en{i}b{b}  0 pulse(0 1.8 10n 2n 2n 190n 500n)")
                lines.append(f"Ven{i}b{b}b en{i}b{b}b 0 pulse(1.8 0 10n 2n 2n 190n 500n)")
            else:
                lines.append(f"Ven{i}b{b}  en{i}b{b}  0 dc 0")
                lines.append(f"Ven{i}b{b}b en{i}b{b}b 0 dc 1.8")
    lines.append("")

    # Instantiate
    inst_ports = ["bl", "vss", "vdd"]
    for i in range(N_INPUTS):
        inst_ports.append(f"in{i}")
    inst_ports += ["phi_e", "phi_eb", "phi_r"]
    for i in range(N_INPUTS):
        for b in range(N_BITS):
            inst_ports.append(f"en{i}b{b}")
            inst_ports.append(f"en{i}b{b}b")

    inst_lines = ["XMAC"]
    chunk = []
    for p in inst_ports:
        chunk.append(p)
        if len(chunk) >= 10:
            inst_lines.append("+ " + " ".join(chunk))
            chunk = []
    if chunk:
        inst_lines.append("+ " + " ".join(chunk))
    inst_lines.append("+ mac_8in4b")
    lines.extend(inst_lines)

    # Calculate expected Vbl
    import numpy as np
    total_q = sum(test_weights[i] * CUNIT * 1e-15 * test_inputs[i] for i in range(N_INPUTS))
    total_c_weight = sum(2**b * CUNIT for b in range(N_BITS)) * N_INPUTS * 1e-15  # all caps
    total_c_bp = total_c_weight * BP_PARASITIC_FRAC
    total_c = total_c_weight + total_c_bp + 80e-15  # +80fF routing
    vbl_expected = total_q / total_c

    lines.append("")
    lines.append(".control")
    lines.append("set wr_vecnames")
    lines.append("tran 0.5n 2.5u uic")
    lines.append("wrdata mac_8in4b_transient.txt v(bl) v(phi_e) v(phi_r)")
    lines.append("meas tran vbl_eval FIND v(bl) AT=780n")
    lines.append("meas tran vbl_eval2 FIND v(bl) AT=1280n")
    lines.append(f'echo "Expected Vbl = {vbl_expected:.6f} V"')
    lines.append('echo "RESULT: vbl_eval = $&vbl_eval"')
    lines.append('echo "RESULT: vbl_eval2 = $&vbl_eval2"')
    lines.append(f"let err_pct = 100 * (vbl_eval2 - {vbl_expected:.6f}) / {vbl_expected:.6f}")
    lines.append('echo "RESULT: error_pct = $&err_pct"')
    lines.append("quit")
    lines.append(".endc")
    lines.append(".end")

    path = os.path.join(WORK_DIR, "tb_8in4b_multiinput.spice")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Generated {path} (expected Vbl = {vbl_expected*1000:.1f} mV)")


def gen_wta_4class():
    """Generate full WTA: 4 MAC units + 3 comparators + priority encoder."""
    lines = []
    lines.append("* VibroSense Block 06: Full 4-Class WTA Classifier")
    lines.append("* 4 × MAC (8in4b) + 3 StrongARM comparators in binary tree")
    lines.append("* Process: SKY130A | Supply: 1.8V")
    lines.append("* Generated by gen_mac_8in4b.py")
    lines.append("")
    lines.append("* Binary tree WTA:")
    lines.append("*   Comp0: bl0 vs bl1 → winner01 (selects higher of class 0,1)")
    lines.append("*   Comp1: bl2 vs bl3 → winner23 (selects higher of class 2,3)")
    lines.append("*   Comp2: winner01 vs winner23 → final winner")
    lines.append("*")
    lines.append("* Output: 2-bit class code (class0=00, class1=01, class2=10, class3=11)")
    lines.append("* For this testbench, we use the comparator outputs directly.")
    lines.append("")

    # This is just the subcircuit definition — testbenches instantiate it
    # For now generate a simple 2-comparator testbench that compares 2 bitline voltages

    lines.append('.subckt wta_2input vinp vinn voutp voutn clk vdd vss')
    lines.append('* Simple WTA for 2 inputs using StrongARM')
    lines.append('.include "strongarm_comp.spice"')
    lines.append('XCOMP vinp vinn voutp voutn clk vdd vss strongarm_comp')
    lines.append('.ends wta_2input')

    path = os.path.join(WORK_DIR, "wta_circuit.spice")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Generated {path}")


def gen_nonoverlap_clkgen():
    """Generate non-overlapping clock generator (Priority 5)."""
    lines = []
    lines.append("* VibroSense Block 06: Non-Overlapping Clock Generator")
    lines.append("* Input: clk_in (master clock)")
    lines.append("* Outputs: phi_s/phi_sb (sample), phi_e/phi_eb (eval), phi_r (reset)")
    lines.append("* Uses cross-coupled NAND gates for guaranteed non-overlap")
    lines.append("* Process: SKY130A")
    lines.append("")
    lines.append("* Simple 3-phase generator using delayed inverter chains")
    lines.append("* Phase timing derived from master clock period")
    lines.append("")
    lines.append(".subckt clkgen_3ph clk_in phi_s phi_sb phi_e phi_eb phi_r vdd vss")
    lines.append("")
    lines.append("* --- Delay elements (inverter chains) ---")
    lines.append("* Each inverter: NMOS W=0.42u L=0.15u, PMOS W=0.84u L=0.15u")
    lines.append("* 2 inverters ≈ 200ps delay at SKY130")
    lines.append("")
    lines.append("* Master clock buffer")
    lines.append("XN_buf1 clk_buf1 clk_in vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_buf1 clk_buf1 clk_in vdd vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
    lines.append("XN_buf2 clk_buf clk_buf1 vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_buf2 clk_buf clk_buf1 vdd vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
    lines.append("")
    lines.append("* Phase generation using NAND-based non-overlapping generator")
    lines.append("* For simplicity: phi_s = clk_buf, phi_e = delayed clk_buf_bar,")
    lines.append("* phi_r = further delayed version")
    lines.append("")
    lines.append("* phi_s = clk_buf (sample when clock high)")
    lines.append("XN_s1 phi_sb clk_buf vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_s1 phi_sb clk_buf vdd vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
    lines.append("XN_s2 phi_s phi_sb vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_s2 phi_s phi_sb vdd vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
    lines.append("")
    lines.append("* Delay chain for phi_e (6 inverters ≈ 1.2ns after phi_s falls)")
    lines.append("XN_d1 d1 phi_sb vss vss sky130_fd_pr__nfet_01v8 W=0.42u L=0.15u")
    lines.append("XP_d1 d1 phi_sb vdd vdd sky130_fd_pr__pfet_01v8 W=0.84u L=0.15u")
    lines.append("XN_d2 d2 d1 vss vss sky130_fd_pr__nfet_01v8 W=0.42u L=0.15u")
    lines.append("XP_d2 d2 d1 vdd vdd sky130_fd_pr__pfet_01v8 W=0.84u L=0.15u")
    lines.append("XN_d3 d3 d2 vss vss sky130_fd_pr__nfet_01v8 W=0.42u L=0.15u")
    lines.append("XP_d3 d3 d2 vdd vdd sky130_fd_pr__pfet_01v8 W=0.84u L=0.15u")
    lines.append("XN_d4 d4 d3 vss vss sky130_fd_pr__nfet_01v8 W=0.42u L=0.15u")
    lines.append("XP_d4 d4 d3 vdd vdd sky130_fd_pr__pfet_01v8 W=0.84u L=0.15u")
    lines.append("* AND(phi_sb, d4) = phi_e enable (only when phi_s is low AND delay has passed)")
    lines.append("* Use NAND + INV")
    lines.append("XN_na1 nand_e1 phi_sb n_na1 vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XN_na2 n_na1 d4 vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_na1 nand_e1 phi_sb vdd vdd sky130_fd_pr__pfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_na2 nand_e1 d4 vdd vdd sky130_fd_pr__pfet_01v8 W=0.84u L=0.15u")
    lines.append("XN_e1 phi_e nand_e1 vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_e1 phi_e nand_e1 vdd vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
    lines.append("XN_eb phi_eb phi_e vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_eb phi_eb phi_e vdd vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
    lines.append("")
    lines.append("* phi_r: active when both phi_s and phi_e are low")
    lines.append("* NOR(phi_s, phi_e) = phi_r")
    lines.append("XN_nr1 phi_r_b phi_s vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XN_nr2 phi_r_b phi_e vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_nr1 n_nr phi_s vdd vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
    lines.append("XP_nr2 phi_r_b phi_e n_nr vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
    lines.append("* Invert for phi_r (active high)")
    lines.append("XN_ri phi_r phi_r_b vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("XP_ri phi_r phi_r_b vdd vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
    lines.append("")
    lines.append(".ends clkgen_3ph")

    path = os.path.join(WORK_DIR, "clkgen_3ph.spice")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Generated {path}")


if __name__ == "__main__":
    print("=" * 60)
    print("Generating full-scale MAC classifier SPICE netlists")
    print("=" * 60)
    gen_mac_8in4b()
    gen_tb_linearity_8in4b()
    gen_tb_multiinput()
    gen_wta_4class()
    gen_nonoverlap_clkgen()
    print("\nDone. Run verify_full.py for simulation.")
