#!/usr/bin/env python3
"""Generate the full 8-input × 4-bit MAC SPICE netlist.
Uses real SKY130 MIM cap subcircuit (sky130_fd_pr__cap_mim_m3_1) instead of ideal C.
Also generates testbenches and clock generator.
"""

import os
import math

WORK_DIR = os.path.dirname(os.path.abspath(__file__))
N_INPUTS = 8
N_BITS = 4
CUNIT_TARGET = 50  # fF target for bit 0

# MIM cap dimensions: solve W=L for C_area + C_fringe ≈ target
# C = W*L*2fF/um² + 2*(W+L)*0.38fF/um
# For square cap (W=L): C = W²×2 + 4W×0.38
MIM_DIMS = {}  # bit -> (W, L, C_actual_fF)
for bit in range(N_BITS):
    target = (2**bit) * CUNIT_TARGET
    # Newton-Raphson for W² × 2 + 4W × 0.38 = target
    W = math.sqrt(target / 2)  # initial guess
    for _ in range(20):
        c = W*W*2 + 4*W*0.38
        dc = 4*W + 4*0.38
        W = W - (c - target) / dc
        W = max(W, 1.0)
    c_actual = W*W*2 + 4*W*0.38
    c_bp = W*W*0.1  # bottom-plate parasitic
    MIM_DIMS[bit] = (round(W, 2), round(W, 2), round(c_actual, 2), round(c_bp, 2))


def gen_mac_8in4b():
    """Generate mac_8in4b.spice with real MIM caps."""
    lines = []
    lines.append("* VibroSense Block 06: Full MAC Unit — 8 inputs × 4-bit weights")
    lines.append("* Process: SKY130A | Supply: 1.8V")
    lines.append("* Capacitors: sky130_fd_pr__cap_mim_m3_1 (real PDK MIM cap model)")
    lines.append("* Generated by gen_mac_8in4b.py")
    lines.append("*")
    for bit in range(N_BITS):
        W, L, c_main, c_bp = MIM_DIMS[bit]
        lines.append(f"* Bit {bit}: W={W}um L={L}um → Cmain={c_main}fF Cbp={c_bp}fF")
    lines.append("")

    # Build port list
    ports = ["bl", "vss", "vdd"]
    for i in range(N_INPUTS):
        ports.append(f"in{i}")
    ports += ["phi_e", "phi_eb", "phi_r"]
    for i in range(N_INPUTS):
        for b in range(N_BITS):
            ports.append(f"en{i}b{b}")
            ports.append(f"en{i}b{b}b")

    port_lines = [".subckt mac_8in4b"]
    chunk = []
    for p in ports:
        chunk.append(p)
        if len(chunk) >= 8:
            port_lines.append("+ " + " ".join(chunk))
            chunk = []
    if chunk:
        port_lines.append("+ " + " ".join(chunk))
    lines.extend(port_lines)
    lines.append("")

    for i in range(N_INPUTS):
        for b in range(N_BITS):
            W, L, c_main, c_bp = MIM_DIMS[b]
            scale = 2**b
            top = f"top{i}b{b}"
            en = f"en{i}b{b}"
            enb = f"en{i}b{b}b"

            lines.append(f"* --- INPUT {i}, BIT {b} ({scale}×Cunit ≈ {c_main}fF MIM, W={W} L={L}) ---")
            # Sample TG
            lines.append(f"XNt{i}b{b} in{i} {en} {top} vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
            lines.append(f"XPt{i}b{b} in{i} {enb} {top} vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
            # Real MIM cap (includes bottom-plate parasitic internally)
            lines.append(f"XC{i}b{b} {top} vss sky130_fd_pr__cap_mim_m3_1 W={W} L={L} MF=1")
            # Eval TG
            lines.append(f"XNe{i}b{b} {top} phi_e bl vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
            lines.append(f"XPe{i}b{b} {top} phi_eb bl vdd sky130_fd_pr__pfet_01v8 W=1.68u L=0.15u")
            # Reset switch
            lines.append(f"XNr{i}b{b} {top} phi_r vss vss sky130_fd_pr__nfet_01v8 W=0.42u L=0.15u")
            lines.append("")

    lines.append("* --- Bitline reset + routing parasitic ---")
    lines.append("XNblrst bl phi_r vss vss sky130_fd_pr__nfet_01v8 W=0.84u L=0.15u")
    lines.append("Cpar bl vss 80f")
    lines.append("")
    lines.append(".ends mac_8in4b")

    path = os.path.join(WORK_DIR, "mac_8in4b.spice")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Generated {path}")

    # Summary
    total_c_main = sum(MIM_DIMS[b][2] for b in range(N_BITS)) * N_INPUTS
    total_c_bp = sum(MIM_DIMS[b][3] for b in range(N_BITS)) * N_INPUTS
    total_bl = total_c_main + total_c_bp + 80
    n_transistors = N_INPUTS * N_BITS * 5 + 1
    print(f"  Transistors: {n_transistors}")
    print(f"  MIM caps: {N_INPUTS * N_BITS} (real sky130_fd_pr__cap_mim_m3_1)")
    print(f"  Total Cmain: {total_c_main:.0f} fF ({total_c_main/1000:.2f} pF)")
    print(f"  Total Cbp: {total_c_bp:.0f} fF")
    print(f"  Bitline total: {total_bl:.0f} fF ({total_bl/1000:.2f} pF)")

    return {
        'n_transistors': n_transistors,
        'total_cmain': total_c_main,
        'total_cbp': total_c_bp,
        'total_bl': total_bl,
        'mim_dims': MIM_DIMS,
    }


def gen_tb_multiinput():
    """Generate testbench: all 8 inputs with different voltages and weights."""
    test_inputs = [0.9, 0.45, 1.35, 0.6, 1.1, 0.3, 0.75, 1.5]
    test_weights = [15, 8, 12, 3, 10, 5, 7, 1]

    lines = []
    lines.append("* TB: 8in4b Multi-Input MAC — real MIM caps")
    lines.append('.lib "sky130_minimal.lib.spice" tt')
    lines.append('.include "sky130_fd_pr__cap_mim_m3_1.spice"')
    lines.append('.include "mac_8in4b.spice"')
    lines.append("")
    lines.append("Vdd vdd 0 dc 1.8")
    lines.append("Vss vss 0 dc 0")
    lines.append("")
    for i in range(N_INPUTS):
        lines.append(f"Vin{i} in{i} 0 dc {test_inputs[i]}")
    lines.append("")

    lines.append("Vphi_e phi_e 0 pulse(0 1.8 220n 2n 2n 100n 500n)")
    lines.append("Vphi_eb phi_eb 0 pulse(1.8 0 220n 2n 2n 100n 500n)")
    lines.append("Vphi_r phi_r 0 pulse(0 1.8 340n 2n 2n 100n 500n)")
    lines.append("")

    for i in range(N_INPUTS):
        w = test_weights[i]
        for b in range(N_BITS):
            bit_on = bool(w & (1 << b))
            if bit_on:
                lines.append(f"Ven{i}b{b}  en{i}b{b}  0 pulse(0 1.8 10n 2n 2n 190n 500n)")
                lines.append(f"Ven{i}b{b}b en{i}b{b}b 0 pulse(1.8 0 10n 2n 2n 190n 500n)")
            else:
                lines.append(f"Ven{i}b{b}  en{i}b{b}  0 dc 0")
                lines.append(f"Ven{i}b{b}b en{i}b{b}b 0 dc 1.8")
    lines.append("")

    # Instantiate
    inst_ports = ["bl", "vss", "vdd"]
    for i in range(N_INPUTS):
        inst_ports.append(f"in{i}")
    inst_ports += ["phi_e", "phi_eb", "phi_r"]
    for i in range(N_INPUTS):
        for b in range(N_BITS):
            inst_ports.append(f"en{i}b{b}")
            inst_ports.append(f"en{i}b{b}b")

    inst_lines = ["XMAC"]
    chunk = []
    for p in inst_ports:
        chunk.append(p)
        if len(chunk) >= 10:
            inst_lines.append("+ " + " ".join(chunk))
            chunk = []
    if chunk:
        inst_lines.append("+ " + " ".join(chunk))
    inst_lines.append("+ mac_8in4b")
    lines.extend(inst_lines)

    # Compute expected Vbl using actual MIM cap values (Cmain only, not Cbp for charge)
    # During sample, TG charges both Cmain AND Cbp (they're from top plate to ground)
    # So effective cap = Cmain + Cbp
    q_total = 0
    c_total_all = 80e-15  # BL parasitic
    for i in range(N_INPUTS):
        w = test_weights[i]
        for b in range(N_BITS):
            c_main = MIM_DIMS[b][2] * 1e-15
            c_bp = MIM_DIMS[b][3] * 1e-15
            c_eff = c_main + c_bp
            c_total_all += c_eff
            if w & (1 << b):
                q_total += c_eff * test_inputs[i]
    vbl_expected = q_total / c_total_all

    lines.append("")
    lines.append(".control")
    lines.append("set wr_vecnames")
    lines.append("tran 0.5n 2.5u uic")
    lines.append("wrdata mac_8in4b_mim_transient.txt v(bl) v(phi_e) v(phi_r)")
    lines.append("meas tran vbl_eval FIND v(bl) AT=780n")
    lines.append("meas tran vbl_eval2 FIND v(bl) AT=1280n")
    lines.append(f'echo "Expected Vbl = {vbl_expected:.6f} V"')
    lines.append('echo "RESULT: vbl_eval = $&vbl_eval"')
    lines.append('echo "RESULT: vbl_eval2 = $&vbl_eval2"')
    lines.append(f"let err_pct = 100 * (vbl_eval2 - {vbl_expected:.6f}) / {vbl_expected:.6f}")
    lines.append('echo "RESULT: error_pct = $&err_pct"')
    lines.append("quit")
    lines.append(".endc")
    lines.append(".end")

    path = os.path.join(WORK_DIR, "tb_8in4b_mim.spice")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Generated {path} (expected Vbl = {vbl_expected*1000:.1f} mV)")


if __name__ == "__main__":
    print("=" * 60)
    print("Generating full-scale MAC with real MIM caps")
    print("=" * 60)
    info = gen_mac_8in4b()
    gen_tb_multiinput()
    print(f"\nMIM cap dimensions:")
    for b in range(N_BITS):
        W, L, c, cbp = MIM_DIMS[b]
        print(f"  Bit {b} ({2**b}×): W={W}um L={L}um → Cmain={c}fF + Cbp={cbp}fF = {c+cbp}fF")
