#!/usr/bin/env python3
"""
Bayesian Optimizer for PGA OTA v2 (Two-Stage Miller)
====================================================
Uses scipy.optimize.minimize (Nelder-Mead) to fine-tune OTA parameters.
Runs ngspice for each evaluation and extracts: gain, UGB, PM, power.

Cost function penalizes spec violations and rewards phase margin.
Logs every evaluation to optimizer_log.csv.
"""

import subprocess
import re
import os
import sys
import csv
import time
import numpy as np
from scipy.optimize import minimize, differential_evolution

WORK_DIR = os.path.dirname(os.path.abspath(__file__))

# Parameter names matching .param in ota_pga_v2.spice
PARAM_NAMES = ["W1", "L1", "W3", "L3", "W5", "L5", "W7", "L7", "W11", "L11", "Cc_val", "Rz_val"]

# Current best values
INITIAL = np.array([5.0, 14.0, 2.0, 2.0, 5.0, 1.0, 5.5, 2.0, 11.4, 14.0, 3.5e-12, 30e3])

# Bounds: ±50% of initial (clamped to reasonable minimums)
BOUNDS = [
    (2.5, 10.0),       # W1
    (7.0, 21.0),        # L1
    (1.0, 4.0),         # W3
    (1.0, 4.0),         # L3
    (2.5, 10.0),        # W5
    (0.5, 2.0),         # L5
    (3.0, 10.0),        # W7
    (1.0, 4.0),         # L7
    (6.0, 17.0),        # W11
    (7.0, 21.0),        # L11
    (2.0e-12, 6.0e-12), # Cc_val
    (15e3, 50e3),       # Rz_val
]

LOG_FILE = os.path.join(WORK_DIR, "optimizer_log.csv")
EVAL_COUNT = 0
BEST_COST = float('inf')
BEST_PARAMS = None


def write_netlist(params):
    """Write ota_pga_v2.spice with given parameters."""
    W1, L1, W3, L3, W5, L5, W7, L7, W11, L11, Cc, Rz = params

    netlist = f"""* VibroSense PGA OTA v2 — Two-Stage Miller Compensated OTA (OPTIMIZER)
* SKY130A Process — auto-generated by optimize_pga_v2.py
* All dimensions in microns — requires .option scale=1e-6 in testbench
* Compensation uses ideal R and C

.param W1={W1:.3f}     L1={L1:.3f}
.param W3={W3:.3f}     L3={L3:.3f}
.param W5={W5:.3f}     L5={L5:.3f}
.param W7={W7:.3f}     L7={L7:.3f}
.param W11={W11:.3f}   L11={L11:.3f}
.param Cc_val={Cc:.4e}
.param Rz_val={Rz:.1f}
.param Rvdd_val=10k
.param Cvdd_val=100n

.subckt ota_pga_v2 vdd gnd inp inn out vbn vbcn vbp vbcp

XM11  otail  vbn    gnd  gnd  sky130_fd_pr__nfet_01v8  w={{W11}}  l={{L11}}
XM1   v_mir  inp    otail gnd  sky130_fd_pr__nfet_01v8  w={{W1}}   l={{L1}}
XM2   v_s1   inn    otail gnd  sky130_fd_pr__nfet_01v8  w={{W1}}   l={{L1}}

Rvdd  vdd  vdd_int  {{Rvdd_val}}
Cvdd  vdd_int  gnd  {{Cvdd_val}}

XM3   v_mir  v_mir  vdd_int  vdd_int  sky130_fd_pr__pfet_01v8   w={{W3}}   l={{L3}}
XM4   v_s1   v_mir  vdd_int  vdd_int  sky130_fd_pr__pfet_01v8   w={{W3}}   l={{L3}}

Rz    v_s1  rz_mid  {{Rz_val}}
Cc    rz_mid  out  {{Cc_val}}

XM5   out  v_s1  vdd_int  vdd_int  sky130_fd_pr__pfet_01v8      w={{W5}}   l={{L5}}
XM7   out  vbn   gnd  gnd  sky130_fd_pr__nfet_01v8      w={{W7}}   l={{L7}}

.ends ota_pga_v2
"""
    with open(os.path.join(WORK_DIR, "ota_pga_v2.spice"), "w") as f:
        f.write(netlist)


def run_sim(spice_file):
    """Run ngspice and return stdout+stderr."""
    try:
        result = subprocess.run(
            ["/usr/bin/ngspice", "-b", spice_file],
            cwd=WORK_DIR,
            capture_output=True, text=True, timeout=120
        )
        return result.stdout + result.stderr
    except:
        return ""


def parse_meas(output, name):
    pattern = rf'{name}\s*=\s*([+-]?\d+\.?\d*[eE][+-]?\d+|[+-]?\d+\.?\d*)'
    match = re.search(pattern, output, re.IGNORECASE)
    if match:
        return float(match.group(1))
    return None


def evaluate(params):
    """Run simulations and compute cost."""
    global EVAL_COUNT, BEST_COST, BEST_PARAMS
    EVAL_COUNT += 1

    write_netlist(params)

    # Run AC testbench
    ac_out = run_sim("tb_pga_v2_ac.spice")
    gain = parse_meas(ac_out, "g10") or parse_meas(ac_out, "gain_peak")
    ugb = parse_meas(ac_out, "ugb")
    phase_ugb = parse_meas(ac_out, "phase_ugb")
    pm = phase_ugb + 180 if phase_ugb is not None else 0

    # Run OP for power
    op_out = run_sim("tb_pga_v2_op.spice")
    id_m11 = parse_meas(op_out, r"@m\.xota\.m11\[id\]")
    id_m7 = parse_meas(op_out, r"@m\.xota\.m7\[id\]")

    if id_m11 is not None and id_m7 is not None:
        power_uW = (abs(id_m11) + abs(id_m7)) * 1e6 * 1.8
    else:
        power_uW = 20.0  # penalty

    if gain is None:
        gain = 0
    if ugb is None:
        ugb = 0

    # Cost function: weighted penalty for spec violations + PM maximization
    cost = 0
    cost += 20.0 * max(0, 65 - gain)           # gain > 65 dB
    cost += 30.0 * max(0, 400e3 - ugb)  / 1e3  # UGB > 400 kHz
    cost += 50.0 * max(0, 60 - pm)             # PM > 60°
    cost += 10.0 * max(0, power_uW - 10)        # power < 10 µW
    cost += -1.0 * pm                            # bonus for higher PM

    # Log
    with open(LOG_FILE, "a", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([EVAL_COUNT, gain, ugb, pm, power_uW, cost] + list(params))

    if cost < BEST_COST:
        BEST_COST = cost
        BEST_PARAMS = params.copy()

    print(f"  [{EVAL_COUNT:3d}] gain={gain:.1f}dB ugb={ugb/1e3:.0f}kHz pm={pm:.1f}° pwr={power_uW:.1f}µW cost={cost:.1f}")
    return cost


def main():
    global EVAL_COUNT, BEST_COST, BEST_PARAMS

    print("=" * 60)
    print("PGA OTA v2 Optimizer — Nelder-Mead + PM maximization")
    print("=" * 60)

    # Initialize log
    with open(LOG_FILE, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["eval", "gain_dB", "ugb_Hz", "pm_deg", "power_uW", "cost"] + PARAM_NAMES)

    # Phase 1: Nelder-Mead from current best
    print("\nPhase 1: Nelder-Mead optimization (max 100 evals)...")
    t0 = time.time()
    result = minimize(
        evaluate,
        INITIAL,
        method='Nelder-Mead',
        options={'maxiter': 100, 'maxfev': 100, 'xatol': 0.01, 'fatol': 0.1}
    )
    elapsed = time.time() - t0
    print(f"\nPhase 1 complete: {EVAL_COUNT} evaluations in {elapsed:.0f}s")
    print(f"Best cost: {BEST_COST:.2f}")

    # Write best parameters back
    write_netlist(BEST_PARAMS)

    # Print summary
    print("\n" + "=" * 60)
    print("OPTIMIZED PARAMETERS:")
    print("=" * 60)
    for name, val in zip(PARAM_NAMES, BEST_PARAMS):
        if "Cc" in name:
            print(f"  {name:8s} = {val*1e12:.2f} pF")
        elif "Rz" in name:
            print(f"  {name:8s} = {val/1e3:.1f} kOhm")
        else:
            print(f"  {name:8s} = {val:.3f}")

    # Final verification
    print("\nRunning final verification...")
    result = subprocess.run(
        [sys.executable, "verify_pga_v2.py"],
        cwd=WORK_DIR, capture_output=True, text=True, timeout=600
    )
    print(result.stdout[-500:] if result.stdout else "No output")
    print(f"Exit code: {result.returncode}")


if __name__ == "__main__":
    main()
