/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "../rtl/digital_top.v:9.1-236.10" *)
module digital_top(clk, rst_n, sck, mosi, cs_n, miso, irq_n, gain, tune1, tune2, tune3, tune4, tune5, weights, thresh, debounce_val, adc_chan, adc_start, adc_data_in, class_result, class_valid
, fsm_sample, fsm_evaluate, fsm_compare, clk_div2, clk_div4, clk_div8, clk_div16);
  (* src = "../rtl/digital_top.v:118.5-133.8" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  wire _155_;
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  wire _156_;
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  wire _157_;
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  wire _158_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _159_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _160_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _161_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _162_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _163_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _164_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _165_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _166_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _167_;
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  wire _168_;
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  wire _169_;
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  wire _170_;
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  wire _171_;
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  wire _172_;
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  wire _173_;
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/digital_top.v:227.7-234.6|../rtl/clk_divider.v:26.20-26.55|../rtl/spi_slave.v:70.25-70.39|../rtl/digital_top.v:145.7-158.6|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _375_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/digital_top.v:227.7-234.6|../rtl/clk_divider.v:26.20-26.55|../rtl/spi_slave.v:70.25-70.39|../rtl/digital_top.v:145.7-158.6|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _376_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/spi_slave.v:70.25-70.39|../rtl/digital_top.v:145.7-158.6|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _377_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/spi_slave.v:70.25-70.39|../rtl/digital_top.v:145.7-158.6|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _378_;
  (* src = "../rtl/digital_top.v:48.24-48.32" *)
  output [1:0] adc_chan;
  wire [1:0] adc_chan;
  (* src = "../rtl/digital_top.v:50.24-50.35" *)
  input [7:0] adc_data_in;
  wire [7:0] adc_data_in;
  (* src = "../rtl/digital_top.v:114.15-114.27" *)
  wire [3:0] adc_done_cnt;
  (* src = "../rtl/digital_top.v:49.24-49.33" *)
  output adc_start;
  wire adc_start;
  (* src = "../rtl/digital_top.v:53.24-53.36" *)
  input [3:0] class_result;
  wire [3:0] class_result;
  (* src = "../rtl/digital_top.v:54.24-54.35" *)
  input class_valid;
  wire class_valid;
  (* src = "../rtl/digital_top.v:18.24-18.27" *)
  input clk;
  wire clk;
  (* src = "../rtl/digital_top.v:65.24-65.33" *)
  output clk_div16;
  wire clk_div16;
  (* src = "../rtl/digital_top.v:62.24-62.32" *)
  output clk_div2;
  wire clk_div2;
  (* src = "../rtl/digital_top.v:63.24-63.32" *)
  output clk_div4;
  wire clk_div4;
  (* src = "../rtl/digital_top.v:64.24-64.32" *)
  output clk_div8;
  wire clk_div8;
  (* src = "../rtl/digital_top.v:24.24-24.28" *)
  input cs_n;
  wire cs_n;
  (* src = "../rtl/digital_top.v:45.24-45.36" *)
  output [3:0] debounce_val;
  wire [3:0] debounce_val;
  (* src = "../rtl/digital_top.v:59.24-59.35" *)
  output fsm_compare;
  wire fsm_compare;
  (* src = "../rtl/digital_top.v:58.24-58.36" *)
  output fsm_evaluate;
  wire fsm_evaluate;
  (* src = "../rtl/digital_top.v:57.24-57.34" *)
  output fsm_sample;
  wire fsm_sample;
  (* src = "../rtl/digital_top.v:31.24-31.28" *)
  output [1:0] gain;
  wire [1:0] gain;
  (* src = "../rtl/digital_top.v:28.24-28.29" *)
  output irq_n;
  wire irq_n;
  (* src = "../rtl/digital_top.v:25.24-25.28" *)
  output miso;
  wire miso;
  (* src = "../rtl/digital_top.v:23.24-23.28" *)
  input mosi;
  wire mosi;
  (* src = "../rtl/digital_top.v:19.24-19.29" *)
  input rst_n;
  wire rst_n;
  (* src = "../rtl/digital_top.v:22.24-22.27" *)
  input sck;
  wire sck;
  (* src = "../rtl/digital_top.v:42.24-42.30" *)
  output [7:0] thresh;
  wire [7:0] thresh;
  (* src = "../rtl/digital_top.v:34.24-34.29" *)
  output [3:0] tune1;
  wire [3:0] tune1;
  (* src = "../rtl/digital_top.v:35.24-35.29" *)
  output [3:0] tune2;
  wire [3:0] tune2;
  (* src = "../rtl/digital_top.v:36.24-36.29" *)
  output [3:0] tune3;
  wire [3:0] tune3;
  (* src = "../rtl/digital_top.v:37.24-37.29" *)
  output [3:0] tune4;
  wire [3:0] tune4;
  (* src = "../rtl/digital_top.v:38.24-38.29" *)
  output [3:0] tune5;
  wire [3:0] tune5;
  (* hdlname = "u_debounce debounce_wr" *)
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:26.31-26.42" *)
  wire \u_debounce.debounce_wr ;
  (* hdlname = "u_debounce detect_count" *)
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:34.23-34.35" *)
  wire [3:0] \u_debounce.detect_count ;
  (* hdlname = "u_debounce irq_assert" *)
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:29.31-29.41" *)
  wire \u_debounce.irq_assert ;
  (* hdlname = "u_debounce last_class" *)
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:35.24-35.34" *)
  wire [3:0] \u_debounce.last_class ;
  (* hdlname = "u_fsm cnt" *)
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:36.25-36.28" *)
  wire [9:0] \u_fsm.cnt ;
  (* hdlname = "u_regfile adc_busy" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:73.9-73.17" *)
  wire \u_regfile.adc_busy ;
  (* hdlname = "u_regfile adc_done" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:42.32-42.40" *)
  wire \u_regfile.adc_done ;
  (* hdlname = "u_regfile regs[12]" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:64.22-64.26" *)
  wire [7:0] \u_regfile.regs[12] ;
  (* hdlname = "u_regfile regs[13]" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:64.22-64.26" *)
  (* unused_bits = "3" *)
  wire [7:0] \u_regfile.regs[13] ;
  (* hdlname = "u_regfile regs[14]" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:64.22-64.26" *)
  wire [7:0] \u_regfile.regs[14] ;
  (* hdlname = "u_regfile status_rd" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:36.32-36.41" *)
  wire \u_regfile.status_rd ;
  (* hdlname = "u_regfile status_valid" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:70.9-70.21" *)
  wire \u_regfile.status_valid ;
  (* hdlname = "u_regfile wr_addr" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:28.32-28.39" *)
  (* unused_bits = "4 5 6" *)
  wire [6:0] \u_regfile.wr_addr ;
  (* hdlname = "u_regfile wr_data" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:29.32-29.39" *)
  wire [7:0] \u_regfile.wr_data ;
  (* hdlname = "u_regfile wr_en" *)
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:27.32-27.37" *)
  wire \u_regfile.wr_en ;
  (* hdlname = "u_spi addr_latched" *)
  (* init = 7'h00 *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:42.16-42.28" *)
  wire [6:0] \u_spi.addr_latched ;
  (* hdlname = "u_spi bit_cnt" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:38.16-38.23" *)
  wire [3:0] \u_spi.bit_cnt ;
  (* hdlname = "u_spi miso_bit" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:54.9-54.17" *)
  wire \u_spi.miso_bit ;
  (* hdlname = "u_spi rd_is_status" *)
  (* init = 1'h0 *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:51.16-51.28" *)
  wire \u_spi.rd_is_status ;
  (* hdlname = "u_spi rd_sync1" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:142.9-142.17" *)
  wire \u_spi.rd_sync1 ;
  (* hdlname = "u_spi rd_sync2" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:142.19-142.27" *)
  wire \u_spi.rd_sync2 ;
  (* hdlname = "u_spi rd_sync3" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:142.29-142.37" *)
  wire \u_spi.rd_sync3 ;
  (* hdlname = "u_spi rd_toggle" *)
  (* init = 1'h0 *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:50.16-50.25" *)
  wire \u_spi.rd_toggle ;
  (* hdlname = "u_spi rw_flag" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:41.16-41.23" *)
  wire \u_spi.rw_flag ;
  (* hdlname = "u_spi shift_in" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:39.16-39.24" *)
  (* unused_bits = "7" *)
  wire [7:0] \u_spi.shift_in ;
  (* hdlname = "u_spi shift_out" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:40.16-40.25" *)
  wire [7:0] \u_spi.shift_out ;
  (* hdlname = "u_spi wr_addr_hold" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:46.16-46.28" *)
  (* unused_bits = "4 5 6" *)
  wire [6:0] \u_spi.wr_addr_hold ;
  (* hdlname = "u_spi wr_data_hold" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:47.16-47.28" *)
  wire [7:0] \u_spi.wr_data_hold ;
  (* hdlname = "u_spi wr_pulse" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:136.10-136.18" *)
  wire \u_spi.wr_pulse ;
  (* hdlname = "u_spi wr_sync1" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:122.9-122.17" *)
  wire \u_spi.wr_sync1 ;
  (* hdlname = "u_spi wr_sync2" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:122.19-122.27" *)
  wire \u_spi.wr_sync2 ;
  (* hdlname = "u_spi wr_sync3" *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:122.29-122.37" *)
  wire \u_spi.wr_sync3 ;
  (* hdlname = "u_spi wr_toggle" *)
  (* init = 1'h0 *)
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:45.16-45.25" *)
  wire \u_spi.wr_toggle ;
  (* src = "../rtl/digital_top.v:41.24-41.31" *)
  output [31:0] weights;
  wire [31:0] weights;
  sky130_fd_sc_hd__clkinv_1 _379_ (
    .A(debounce_val[2]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__clkinv_1 _380_ (
    .A(\u_debounce.irq_assert ),
    .Y(irq_n)
  );
  sky130_fd_sc_hd__clkinv_1 _381_ (
    .A(cs_n),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _382_ (
    .A(clk_div2),
    .Y(_375_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _383_ (
    .A(\u_spi.bit_cnt [3]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__clkinv_1 _384_ (
    .A(\u_spi.bit_cnt [0]),
    .Y(_377_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _385_ (
    .A(\u_regfile.adc_busy ),
    .Y(_177_)
  );
  sky130_fd_sc_hd__clkinv_1 _386_ (
    .A(\u_regfile.regs[13] [2]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__clkinv_1 _387_ (
    .A(\u_debounce.debounce_wr ),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _388_ (
    .A(\u_spi.addr_latched [0]),
    .B(\u_spi.addr_latched [1]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand2b_1 _389_ (
    .A_N(\u_spi.addr_latched [3]),
    .B(\u_spi.addr_latched [2]),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nor2_1 _390_ (
    .A(_180_),
    .B(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nand2b_1 _391_ (
    .A_N(\u_spi.addr_latched [0]),
    .B(\u_spi.addr_latched [1]),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nand2_1 _392_ (
    .A(\u_spi.addr_latched [2]),
    .B(\u_spi.addr_latched [3]),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nor2_1 _393_ (
    .A(_183_),
    .B(_184_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2b_1 _394_ (
    .A_N(\u_spi.addr_latched [2]),
    .B(\u_spi.addr_latched [3]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nand2b_1 _395_ (
    .A_N(\u_spi.addr_latched [1]),
    .B(\u_spi.addr_latched [0]),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nor2_1 _396_ (
    .A(_186_),
    .B(_187_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nor2_1 _397_ (
    .A(_183_),
    .B(_186_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _398_ (
    .A(\u_spi.addr_latched [0]),
    .B(\u_spi.addr_latched [1]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor3_1 _399_ (
    .A(\u_spi.addr_latched [0]),
    .B(\u_spi.addr_latched [1]),
    .C(_186_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nor2_1 _400_ (
    .A(_181_),
    .B(_183_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__a222oi_1 _401_ (
    .A1(weights[30]),
    .A2(_188_),
    .B1(_191_),
    .B2(weights[22]),
    .C1(weights[14]),
    .C2(_182_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a222oi_1 _402_ (
    .A1(thresh[6]),
    .A2(_189_),
    .B1(_192_),
    .B2(weights[6]),
    .C1(\u_regfile.regs[14] [6]),
    .C2(_185_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nor4_1 _403_ (
    .A(_176_),
    .B(\u_spi.bit_cnt [0]),
    .C(\u_spi.bit_cnt [1]),
    .D(\u_spi.bit_cnt [2]),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nor3_1 _404_ (
    .A(\u_spi.addr_latched [4]),
    .B(\u_spi.addr_latched [5]),
    .C(\u_spi.addr_latched [6]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__o211ai_1 _405_ (
    .A1(_180_),
    .A2(_184_),
    .B1(_195_),
    .C1(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__a21oi_1 _406_ (
    .A1(_193_),
    .A2(_194_),
    .B1(_197_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor2_1 _407_ (
    .A(_176_),
    .B(_195_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a221o_1 _408_ (
    .A1(\u_spi.shift_out [7]),
    .A2(_176_),
    .B1(_199_),
    .B2(\u_spi.shift_out [6]),
    .C1(_198_),
    .X(_134_)
  );
  sky130_fd_sc_hd__a222oi_1 _409_ (
    .A1(weights[29]),
    .A2(_188_),
    .B1(_191_),
    .B2(weights[21]),
    .C1(weights[13]),
    .C2(_182_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__a222oi_1 _410_ (
    .A1(thresh[5]),
    .A2(_189_),
    .B1(_192_),
    .B2(weights[5]),
    .C1(\u_regfile.regs[14] [5]),
    .C2(_185_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__a21oi_1 _411_ (
    .A1(_200_),
    .A2(_201_),
    .B1(_197_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__a221o_1 _412_ (
    .A1(\u_spi.shift_out [6]),
    .A2(_176_),
    .B1(_199_),
    .B2(\u_spi.shift_out [5]),
    .C1(_202_),
    .X(_133_)
  );
  sky130_fd_sc_hd__a222oi_1 _413_ (
    .A1(weights[28]),
    .A2(_188_),
    .B1(_191_),
    .B2(weights[20]),
    .C1(weights[12]),
    .C2(_182_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__a222oi_1 _414_ (
    .A1(thresh[4]),
    .A2(_189_),
    .B1(_192_),
    .B2(weights[4]),
    .C1(\u_regfile.regs[14] [4]),
    .C2(_185_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__a21oi_1 _415_ (
    .A1(_203_),
    .A2(_204_),
    .B1(_197_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__a221o_1 _416_ (
    .A1(\u_spi.shift_out [5]),
    .A2(_176_),
    .B1(_199_),
    .B2(\u_spi.shift_out [4]),
    .C1(_205_),
    .X(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _417_ (
    .A(_180_),
    .B(_186_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__a22oi_1 _418_ (
    .A1(\u_regfile.regs[14] [3]),
    .A2(_185_),
    .B1(_206_),
    .B2(debounce_val[3]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nor3_1 _419_ (
    .A(\u_spi.addr_latched [0]),
    .B(\u_spi.addr_latched [1]),
    .C(_181_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nor2_1 _420_ (
    .A(\u_spi.addr_latched [2]),
    .B(\u_spi.addr_latched [3]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nor3_1 _421_ (
    .A(\u_spi.addr_latched [2]),
    .B(\u_spi.addr_latched [3]),
    .C(_180_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__a22oi_1 _422_ (
    .A1(weights[11]),
    .A2(_182_),
    .B1(_191_),
    .B2(weights[19]),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nor3_1 _423_ (
    .A(\u_spi.addr_latched [0]),
    .B(\u_spi.addr_latched [1]),
    .C(_184_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nand2_1 _424_ (
    .A(\u_regfile.regs[12] [3]),
    .B(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor3_1 _425_ (
    .A(\u_spi.addr_latched [2]),
    .B(\u_spi.addr_latched [3]),
    .C(_187_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor2_1 _426_ (
    .A(_184_),
    .B(_187_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(_181_),
    .B(_187_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand2_1 _428_ (
    .A(thresh[3]),
    .B(_189_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nor3_1 _429_ (
    .A(\u_spi.addr_latched [2]),
    .B(\u_spi.addr_latched [3]),
    .C(_183_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand2_1 _430_ (
    .A(weights[3]),
    .B(_192_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__a22oi_1 _431_ (
    .A1(tune1[3]),
    .A2(_214_),
    .B1(_216_),
    .B2(tune5[3]),
    .Y(_220_)
  );
  sky130_fd_sc_hd__a222oi_1 _432_ (
    .A1(weights[27]),
    .A2(_188_),
    .B1(_208_),
    .B2(tune4[3]),
    .C1(_210_),
    .C2(tune3[3]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand4_1 _433_ (
    .A(_207_),
    .B(_211_),
    .C(_217_),
    .D(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__a22oi_1 _434_ (
    .A1(\u_regfile.adc_busy ),
    .A2(_215_),
    .B1(_218_),
    .B2(tune2[3]),
    .Y(_223_)
  );
  sky130_fd_sc_hd__nand4_1 _435_ (
    .A(_213_),
    .B(_219_),
    .C(_220_),
    .D(_223_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nor2_1 _436_ (
    .A(_222_),
    .B(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__a22oi_1 _437_ (
    .A1(\u_spi.shift_out [4]),
    .A2(_176_),
    .B1(_199_),
    .B2(\u_spi.shift_out [3]),
    .Y(_226_)
  );
  sky130_fd_sc_hd__o21ai_0 _438_ (
    .A1(_197_),
    .A2(_225_),
    .B1(_226_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a22oi_1 _439_ (
    .A1(\u_regfile.regs[14] [2]),
    .A2(_185_),
    .B1(_206_),
    .B2(debounce_val[2]),
    .Y(_227_)
  );
  sky130_fd_sc_hd__a22oi_1 _440_ (
    .A1(weights[10]),
    .A2(_182_),
    .B1(_191_),
    .B2(weights[18]),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nand2_1 _441_ (
    .A(\u_regfile.regs[12] [2]),
    .B(_212_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(thresh[2]),
    .B(_189_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__nand2_1 _443_ (
    .A(weights[2]),
    .B(_192_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__a22oi_1 _444_ (
    .A1(tune1[2]),
    .A2(_214_),
    .B1(_216_),
    .B2(tune5[2]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__a222oi_1 _445_ (
    .A1(weights[26]),
    .A2(_188_),
    .B1(_208_),
    .B2(tune4[2]),
    .C1(_210_),
    .C2(tune3[2]),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nand4_1 _446_ (
    .A(_227_),
    .B(_228_),
    .C(_230_),
    .D(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__a22oi_1 _447_ (
    .A1(\u_regfile.regs[13] [2]),
    .A2(_215_),
    .B1(_218_),
    .B2(tune2[2]),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nand4_1 _448_ (
    .A(_229_),
    .B(_231_),
    .C(_232_),
    .D(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nor2_1 _449_ (
    .A(_234_),
    .B(_236_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__a22oi_1 _450_ (
    .A1(\u_spi.shift_out [3]),
    .A2(_176_),
    .B1(_199_),
    .B2(\u_spi.shift_out [2]),
    .Y(_238_)
  );
  sky130_fd_sc_hd__o21ai_0 _451_ (
    .A1(_197_),
    .A2(_237_),
    .B1(_238_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _452_ (
    .A(weights[25]),
    .B(_188_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__a22oi_1 _453_ (
    .A1(weights[17]),
    .A2(_191_),
    .B1(_208_),
    .B2(tune4[1]),
    .Y(_240_)
  );
  sky130_fd_sc_hd__a22oi_1 _454_ (
    .A1(\u_regfile.regs[14] [1]),
    .A2(_185_),
    .B1(_214_),
    .B2(tune1[1]),
    .Y(_241_)
  );
  sky130_fd_sc_hd__a22oi_1 _455_ (
    .A1(weights[1]),
    .A2(_192_),
    .B1(_218_),
    .B2(tune2[1]),
    .Y(_242_)
  );
  sky130_fd_sc_hd__a32oi_1 _456_ (
    .A1(gain[1]),
    .A2(_190_),
    .A3(_209_),
    .B1(_216_),
    .B2(tune5[1]),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand4_1 _457_ (
    .A(_240_),
    .B(_241_),
    .C(_242_),
    .D(_243_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a22oi_1 _458_ (
    .A1(\u_regfile.regs[12] [1]),
    .A2(_212_),
    .B1(_215_),
    .B2(adc_chan[1]),
    .Y(_245_)
  );
  sky130_fd_sc_hd__a22oi_1 _459_ (
    .A1(thresh[1]),
    .A2(_189_),
    .B1(_206_),
    .B2(debounce_val[1]),
    .Y(_246_)
  );
  sky130_fd_sc_hd__a22oi_1 _460_ (
    .A1(weights[9]),
    .A2(_182_),
    .B1(_210_),
    .B2(tune3[1]),
    .Y(_247_)
  );
  sky130_fd_sc_hd__nand4_1 _461_ (
    .A(_239_),
    .B(_245_),
    .C(_246_),
    .D(_247_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nor2_1 _462_ (
    .A(_244_),
    .B(_248_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__a22oi_1 _463_ (
    .A1(\u_spi.shift_out [2]),
    .A2(_176_),
    .B1(_199_),
    .B2(\u_spi.shift_out [1]),
    .Y(_250_)
  );
  sky130_fd_sc_hd__o21ai_0 _464_ (
    .A1(_197_),
    .A2(_249_),
    .B1(_250_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _465_ (
    .A(weights[24]),
    .B(_188_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__a22oi_1 _466_ (
    .A1(weights[16]),
    .A2(_191_),
    .B1(_208_),
    .B2(tune4[0]),
    .Y(_252_)
  );
  sky130_fd_sc_hd__a22oi_1 _467_ (
    .A1(\u_regfile.regs[14] [0]),
    .A2(_185_),
    .B1(_214_),
    .B2(tune1[0]),
    .Y(_253_)
  );
  sky130_fd_sc_hd__a22oi_1 _468_ (
    .A1(weights[0]),
    .A2(_192_),
    .B1(_218_),
    .B2(tune2[0]),
    .Y(_254_)
  );
  sky130_fd_sc_hd__a32oi_1 _469_ (
    .A1(gain[0]),
    .A2(_190_),
    .A3(_209_),
    .B1(_216_),
    .B2(tune5[0]),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nand4_1 _470_ (
    .A(_252_),
    .B(_253_),
    .C(_254_),
    .D(_255_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__a22oi_1 _471_ (
    .A1(\u_regfile.regs[12] [0]),
    .A2(_212_),
    .B1(_215_),
    .B2(adc_chan[0]),
    .Y(_257_)
  );
  sky130_fd_sc_hd__a22oi_1 _472_ (
    .A1(thresh[0]),
    .A2(_189_),
    .B1(_206_),
    .B2(debounce_val[0]),
    .Y(_258_)
  );
  sky130_fd_sc_hd__a22oi_1 _473_ (
    .A1(weights[8]),
    .A2(_182_),
    .B1(_210_),
    .B2(tune3[0]),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nand4_1 _474_ (
    .A(_251_),
    .B(_257_),
    .C(_258_),
    .D(_259_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nor2_1 _475_ (
    .A(_256_),
    .B(_260_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__a22oi_1 _476_ (
    .A1(\u_spi.shift_out [1]),
    .A2(_176_),
    .B1(_199_),
    .B2(\u_spi.shift_out [0]),
    .Y(_262_)
  );
  sky130_fd_sc_hd__o21ai_0 _477_ (
    .A1(_197_),
    .A2(_261_),
    .B1(_262_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _478_ (
    .A(\u_spi.shift_out [0]),
    .SLEEP(\u_spi.bit_cnt [3]),
    .X(_127_)
  );
  sky130_fd_sc_hd__nand3_1 _479_ (
    .A(\u_spi.bit_cnt [0]),
    .B(\u_spi.bit_cnt [1]),
    .C(\u_spi.bit_cnt [2]),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2_1 _480_ (
    .A(\u_spi.bit_cnt [3]),
    .B(_263_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__mux2_1 _481_ (
    .A0(\u_spi.rw_flag ),
    .A1(\u_spi.shift_in [6]),
    .S(_264_),
    .X(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _482_ (
    .A(\u_regfile.wr_addr [0]),
    .B(\u_regfile.wr_en ),
    .Y(_265_)
  );
  sky130_fd_sc_hd__nor2_1 _483_ (
    .A(\u_regfile.wr_addr [1]),
    .B(_265_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _484_ (
    .A(\u_regfile.wr_addr [1]),
    .SLEEP(_265_),
    .X(_267_)
  );
  sky130_fd_sc_hd__nand3_1 _485_ (
    .A(\u_regfile.wr_addr [2]),
    .B(\u_regfile.wr_addr [3]),
    .C(_266_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__mux2_1 _486_ (
    .A0(\u_regfile.wr_data [0]),
    .A1(adc_chan[0]),
    .S(_268_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _487_ (
    .A0(\u_regfile.wr_data [1]),
    .A1(adc_chan[1]),
    .S(_268_),
    .X(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _488_ (
    .A(\u_fsm.cnt [0]),
    .B(\u_fsm.cnt [1]),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nor2_1 _489_ (
    .A(\u_fsm.cnt [8]),
    .B(\u_fsm.cnt [9]),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nand2_1 _490_ (
    .A(rst_n),
    .B(_270_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__or4_1 _491_ (
    .A(\u_fsm.cnt [2]),
    .B(\u_fsm.cnt [3]),
    .C(\u_fsm.cnt [4]),
    .D(\u_fsm.cnt [5]),
    .X(_272_)
  );
  sky130_fd_sc_hd__nand2_1 _492_ (
    .A(\u_fsm.cnt [6]),
    .B(\u_fsm.cnt [7]),
    .Y(_273_)
  );
  sky130_fd_sc_hd__nor3_1 _493_ (
    .A(_271_),
    .B(_272_),
    .C(_273_),
    .Y(fsm_compare)
  );
  sky130_fd_sc_hd__nor4_1 _494_ (
    .A(_269_),
    .B(_271_),
    .C(_272_),
    .D(_273_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__or4_1 _495_ (
    .A(_269_),
    .B(_271_),
    .C(_272_),
    .D(_273_),
    .X(_275_)
  );
  sky130_fd_sc_hd__nand2_1 _496_ (
    .A(\u_regfile.regs[12] [0]),
    .B(_275_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nand2_1 _497_ (
    .A(class_result[0]),
    .B(_274_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__nand2_1 _498_ (
    .A(_276_),
    .B(_277_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _499_ (
    .A(\u_regfile.regs[12] [1]),
    .B(_275_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__nand2_1 _500_ (
    .A(class_result[1]),
    .B(_274_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nand2_1 _501_ (
    .A(_278_),
    .B(_279_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _502_ (
    .A(\u_regfile.regs[12] [2]),
    .B(_275_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__nand2_1 _503_ (
    .A(class_result[2]),
    .B(_274_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nand2_1 _504_ (
    .A(_280_),
    .B(_281_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _505_ (
    .A(\u_regfile.regs[12] [3]),
    .B(_275_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__nand2_1 _506_ (
    .A(class_result[3]),
    .B(_274_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__nand2_1 _507_ (
    .A(_282_),
    .B(_283_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _508_ (
    .A(\u_regfile.wr_addr [3]),
    .SLEEP(\u_regfile.wr_addr [2]),
    .X(_284_)
  );
  sky130_fd_sc_hd__nand2b_1 _509_ (
    .A_N(\u_regfile.wr_addr [2]),
    .B(\u_regfile.wr_addr [3]),
    .Y(_285_)
  );
  sky130_fd_sc_hd__nand3b_1 _510_ (
    .A_N(\u_regfile.wr_addr [0]),
    .B(\u_regfile.wr_addr [1]),
    .C(\u_regfile.wr_en ),
    .Y(_286_)
  );
  sky130_fd_sc_hd__nor2_1 _511_ (
    .A(_285_),
    .B(_286_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__mux2_1 _512_ (
    .A0(thresh[0]),
    .A1(\u_regfile.wr_data [0]),
    .S(_287_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _513_ (
    .A0(thresh[1]),
    .A1(\u_regfile.wr_data [1]),
    .S(_287_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _514_ (
    .A0(thresh[2]),
    .A1(\u_regfile.wr_data [2]),
    .S(_287_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _515_ (
    .A0(thresh[3]),
    .A1(\u_regfile.wr_data [3]),
    .S(_287_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _516_ (
    .A0(thresh[4]),
    .A1(\u_regfile.wr_data [4]),
    .S(_287_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _517_ (
    .A0(thresh[5]),
    .A1(\u_regfile.wr_data [5]),
    .S(_287_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _518_ (
    .A0(thresh[6]),
    .A1(\u_regfile.wr_data [6]),
    .S(_287_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _519_ (
    .A0(thresh[7]),
    .A1(\u_regfile.wr_data [7]),
    .S(_287_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _520_ (
    .A(_267_),
    .B(_285_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__mux2_1 _521_ (
    .A0(weights[24]),
    .A1(\u_regfile.wr_data [0]),
    .S(_288_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _522_ (
    .A0(weights[25]),
    .A1(\u_regfile.wr_data [1]),
    .S(_288_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _523_ (
    .A0(weights[26]),
    .A1(\u_regfile.wr_data [2]),
    .S(_288_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _524_ (
    .A0(weights[27]),
    .A1(\u_regfile.wr_data [3]),
    .S(_288_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _525_ (
    .A0(weights[28]),
    .A1(\u_regfile.wr_data [4]),
    .S(_288_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _526_ (
    .A0(weights[29]),
    .A1(\u_regfile.wr_data [5]),
    .S(_288_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _527_ (
    .A0(weights[30]),
    .A1(\u_regfile.wr_data [6]),
    .S(_288_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _528_ (
    .A0(weights[31]),
    .A1(\u_regfile.wr_data [7]),
    .S(_288_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _529_ (
    .A(\u_regfile.wr_addr [0]),
    .B(\u_regfile.wr_addr [1]),
    .Y(_289_)
  );
  sky130_fd_sc_hd__nand3_1 _530_ (
    .A(\u_regfile.wr_en ),
    .B(_284_),
    .C(_289_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__mux2_1 _531_ (
    .A0(\u_regfile.wr_data [0]),
    .A1(weights[16]),
    .S(_290_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _532_ (
    .A0(\u_regfile.wr_data [1]),
    .A1(weights[17]),
    .S(_290_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _533_ (
    .A0(\u_regfile.wr_data [2]),
    .A1(weights[18]),
    .S(_290_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _534_ (
    .A0(\u_regfile.wr_data [3]),
    .A1(weights[19]),
    .S(_290_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _535_ (
    .A0(\u_regfile.wr_data [4]),
    .A1(weights[20]),
    .S(_290_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _536_ (
    .A0(\u_regfile.wr_data [5]),
    .A1(weights[21]),
    .S(_290_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _537_ (
    .A0(\u_regfile.wr_data [6]),
    .A1(weights[22]),
    .S(_290_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _538_ (
    .A0(\u_regfile.wr_data [7]),
    .A1(weights[23]),
    .S(_290_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2b_1 _539_ (
    .A_N(\u_regfile.wr_addr [3]),
    .B(\u_regfile.wr_addr [2]),
    .Y(_291_)
  );
  sky130_fd_sc_hd__nand3_1 _540_ (
    .A(\u_regfile.wr_addr [0]),
    .B(\u_regfile.wr_addr [1]),
    .C(\u_regfile.wr_en ),
    .Y(_292_)
  );
  sky130_fd_sc_hd__nor2_1 _541_ (
    .A(_291_),
    .B(_292_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__mux2_1 _542_ (
    .A0(weights[8]),
    .A1(\u_regfile.wr_data [0]),
    .S(_293_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _543_ (
    .A0(weights[9]),
    .A1(\u_regfile.wr_data [1]),
    .S(_293_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _544_ (
    .A0(weights[10]),
    .A1(\u_regfile.wr_data [2]),
    .S(_293_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _545_ (
    .A0(weights[11]),
    .A1(\u_regfile.wr_data [3]),
    .S(_293_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _546_ (
    .A0(weights[12]),
    .A1(\u_regfile.wr_data [4]),
    .S(_293_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _547_ (
    .A0(weights[13]),
    .A1(\u_regfile.wr_data [5]),
    .S(_293_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _548_ (
    .A0(weights[14]),
    .A1(\u_regfile.wr_data [6]),
    .S(_293_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _549_ (
    .A0(weights[15]),
    .A1(\u_regfile.wr_data [7]),
    .S(_293_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _550_ (
    .A(_286_),
    .B(_291_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__mux2_1 _551_ (
    .A0(weights[0]),
    .A1(\u_regfile.wr_data [0]),
    .S(_294_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _552_ (
    .A0(weights[1]),
    .A1(\u_regfile.wr_data [1]),
    .S(_294_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _553_ (
    .A0(weights[2]),
    .A1(\u_regfile.wr_data [2]),
    .S(_294_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _554_ (
    .A0(weights[3]),
    .A1(\u_regfile.wr_data [3]),
    .S(_294_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _555_ (
    .A0(weights[4]),
    .A1(\u_regfile.wr_data [4]),
    .S(_294_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _556_ (
    .A0(weights[5]),
    .A1(\u_regfile.wr_data [5]),
    .S(_294_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _557_ (
    .A0(weights[6]),
    .A1(\u_regfile.wr_data [6]),
    .S(_294_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _558_ (
    .A0(weights[7]),
    .A1(\u_regfile.wr_data [7]),
    .S(_294_),
    .X(_060_)
  );
  sky130_fd_sc_hd__and4_1 _559_ (
    .A(\u_regfile.wr_addr [0]),
    .B(\u_regfile.wr_addr [1]),
    .C(\u_regfile.wr_en ),
    .D(_284_),
    .X(_171_)
  );
  sky130_fd_sc_hd__mux2_1 _560_ (
    .A0(debounce_val[0]),
    .A1(\u_regfile.wr_data [0]),
    .S(_171_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _561_ (
    .A0(debounce_val[1]),
    .A1(\u_regfile.wr_data [1]),
    .S(_171_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _562_ (
    .A(\u_regfile.wr_data [2]),
    .B(_171_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__o21ai_0 _563_ (
    .A1(_175_),
    .A2(_171_),
    .B1(_295_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _564_ (
    .A0(debounce_val[3]),
    .A1(\u_regfile.wr_data [3]),
    .S(_171_),
    .X(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _565_ (
    .A(_267_),
    .B(_291_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__mux2_1 _566_ (
    .A0(tune5[0]),
    .A1(\u_regfile.wr_data [0]),
    .S(_296_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _567_ (
    .A0(tune5[1]),
    .A1(\u_regfile.wr_data [1]),
    .S(_296_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _568_ (
    .A0(tune5[2]),
    .A1(\u_regfile.wr_data [2]),
    .S(_296_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _569_ (
    .A0(tune5[3]),
    .A1(\u_regfile.wr_data [3]),
    .S(_296_),
    .X(_068_)
  );
  sky130_fd_sc_hd__nand4b_1 _570_ (
    .A_N(\u_regfile.wr_addr [3]),
    .B(\u_regfile.wr_en ),
    .C(_289_),
    .D(\u_regfile.wr_addr [2]),
    .Y(_297_)
  );
  sky130_fd_sc_hd__mux2_1 _571_ (
    .A0(\u_regfile.wr_data [0]),
    .A1(tune4[0]),
    .S(_297_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _572_ (
    .A0(\u_regfile.wr_data [1]),
    .A1(tune4[1]),
    .S(_297_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _573_ (
    .A0(\u_regfile.wr_data [2]),
    .A1(tune4[2]),
    .S(_297_),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2_1 _574_ (
    .A0(\u_regfile.wr_data [3]),
    .A1(tune4[3]),
    .S(_297_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _575_ (
    .A(\u_regfile.wr_addr [2]),
    .B(\u_regfile.wr_addr [3]),
    .Y(_298_)
  );
  sky130_fd_sc_hd__nand2b_1 _576_ (
    .A_N(_292_),
    .B(_298_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__mux2_1 _577_ (
    .A0(\u_regfile.wr_data [0]),
    .A1(tune3[0]),
    .S(_299_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _578_ (
    .A0(\u_regfile.wr_data [1]),
    .A1(tune3[1]),
    .S(_299_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _579_ (
    .A0(\u_regfile.wr_data [2]),
    .A1(tune3[2]),
    .S(_299_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _580_ (
    .A0(\u_regfile.wr_data [3]),
    .A1(tune3[3]),
    .S(_299_),
    .X(_076_)
  );
  sky130_fd_sc_hd__nand2b_1 _581_ (
    .A_N(_286_),
    .B(_298_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__mux2_1 _582_ (
    .A0(\u_regfile.wr_data [0]),
    .A1(tune2[0]),
    .S(_300_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2_1 _583_ (
    .A0(\u_regfile.wr_data [1]),
    .A1(tune2[1]),
    .S(_300_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _584_ (
    .A0(\u_regfile.wr_data [2]),
    .A1(tune2[2]),
    .S(_300_),
    .X(_079_)
  );
  sky130_fd_sc_hd__mux2_1 _585_ (
    .A0(\u_regfile.wr_data [3]),
    .A1(tune2[3]),
    .S(_300_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _586_ (
    .A(_266_),
    .B(_298_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__mux2_1 _587_ (
    .A0(\u_regfile.wr_data [0]),
    .A1(tune1[0]),
    .S(_301_),
    .X(_081_)
  );
  sky130_fd_sc_hd__mux2_1 _588_ (
    .A0(\u_regfile.wr_data [1]),
    .A1(tune1[1]),
    .S(_301_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_1 _589_ (
    .A0(\u_regfile.wr_data [2]),
    .A1(tune1[2]),
    .S(_301_),
    .X(_083_)
  );
  sky130_fd_sc_hd__mux2_1 _590_ (
    .A0(\u_regfile.wr_data [3]),
    .A1(tune1[3]),
    .S(_301_),
    .X(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _591_ (
    .A(\u_regfile.status_valid ),
    .B(_274_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__nor2_1 _592_ (
    .A(\u_regfile.status_rd ),
    .B(_302_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _593_ (
    .A(\u_debounce.last_class [0]),
    .B(_275_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__nand2_1 _594_ (
    .A(_277_),
    .B(_303_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _595_ (
    .A(\u_debounce.last_class [1]),
    .B(_275_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__nand2_1 _596_ (
    .A(_279_),
    .B(_304_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _597_ (
    .A(\u_debounce.last_class [2]),
    .B(_275_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__nand2_1 _598_ (
    .A(_281_),
    .B(_305_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _599_ (
    .A(\u_debounce.last_class [3]),
    .B(_275_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__nand2_1 _600_ (
    .A(_283_),
    .B(_306_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _601_ (
    .A(adc_done_cnt[2]),
    .B(adc_done_cnt[3]),
    .Y(_307_)
  );
  sky130_fd_sc_hd__nor2_1 _602_ (
    .A(adc_done_cnt[0]),
    .B(adc_done_cnt[1]),
    .Y(_308_)
  );
  sky130_fd_sc_hd__a211oi_1 _603_ (
    .A1(_307_),
    .A2(_308_),
    .B1(adc_done_cnt[0]),
    .C1(adc_start),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a21oi_1 _604_ (
    .A1(adc_done_cnt[0]),
    .A2(adc_done_cnt[1]),
    .B1(adc_start),
    .Y(_309_)
  );
  sky130_fd_sc_hd__o31ai_1 _605_ (
    .A1(adc_done_cnt[0]),
    .A2(adc_done_cnt[1]),
    .A3(_307_),
    .B1(_309_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__o21ai_0 _606_ (
    .A1(adc_done_cnt[0]),
    .A2(adc_done_cnt[1]),
    .B1(adc_done_cnt[2]),
    .Y(_310_)
  );
  sky130_fd_sc_hd__or3_1 _607_ (
    .A(adc_done_cnt[0]),
    .B(adc_done_cnt[1]),
    .C(adc_done_cnt[2]),
    .X(_311_)
  );
  sky130_fd_sc_hd__a221oi_1 _608_ (
    .A1(_307_),
    .A2(_308_),
    .B1(_310_),
    .B2(_311_),
    .C1(adc_start),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a21o_1 _609_ (
    .A1(adc_done_cnt[3]),
    .A2(_311_),
    .B1(adc_start),
    .X(_093_)
  );
  sky130_fd_sc_hd__nand3_1 _610_ (
    .A(\u_regfile.wr_en ),
    .B(_289_),
    .C(_298_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__mux2_1 _611_ (
    .A0(\u_regfile.wr_data [0]),
    .A1(gain[0]),
    .S(_312_),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_1 _612_ (
    .A0(\u_regfile.wr_data [1]),
    .A1(gain[1]),
    .S(_312_),
    .X(_095_)
  );
  sky130_fd_sc_hd__nand3_1 _613_ (
    .A(\u_debounce.detect_count [0]),
    .B(\u_debounce.detect_count [1]),
    .C(\u_debounce.detect_count [2]),
    .Y(_313_)
  );
  sky130_fd_sc_hd__nand4_1 _614_ (
    .A(\u_debounce.detect_count [0]),
    .B(\u_debounce.detect_count [1]),
    .C(\u_debounce.detect_count [2]),
    .D(\u_debounce.detect_count [3]),
    .Y(_314_)
  );
  sky130_fd_sc_hd__xor2_1 _615_ (
    .A(\u_debounce.detect_count [3]),
    .B(_313_),
    .X(_315_)
  );
  sky130_fd_sc_hd__a21oi_1 _616_ (
    .A1(\u_debounce.detect_count [0]),
    .A2(\u_debounce.detect_count [1]),
    .B1(\u_debounce.detect_count [2]),
    .Y(_316_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _617_ (
    .A(_313_),
    .SLEEP(_316_),
    .X(_317_)
  );
  sky130_fd_sc_hd__xnor2_1 _618_ (
    .A(\u_debounce.detect_count [0]),
    .B(\u_debounce.detect_count [1]),
    .Y(_318_)
  );
  sky130_fd_sc_hd__o211a_1 _619_ (
    .A1(debounce_val[1]),
    .A2(\u_debounce.detect_count [1]),
    .B1(\u_debounce.detect_count [0]),
    .C1(debounce_val[0]),
    .X(_319_)
  );
  sky130_fd_sc_hd__a21oi_1 _620_ (
    .A1(debounce_val[1]),
    .A2(_318_),
    .B1(_319_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__maj3_1 _621_ (
    .A(_175_),
    .B(_317_),
    .C(_320_),
    .X(_321_)
  );
  sky130_fd_sc_hd__a21boi_0 _622_ (
    .A1(debounce_val[3]),
    .A2(_315_),
    .B1_N(_321_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__o21ai_0 _623_ (
    .A1(debounce_val[3]),
    .A2(_315_),
    .B1(_314_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__o21ai_0 _624_ (
    .A1(_322_),
    .A2(_323_),
    .B1(_274_),
    .Y(_324_)
  );
  sky130_fd_sc_hd__or4_1 _625_ (
    .A(class_result[0]),
    .B(class_result[1]),
    .C(class_result[2]),
    .D(class_result[3]),
    .X(_325_)
  );
  sky130_fd_sc_hd__xnor2_1 _626_ (
    .A(class_result[2]),
    .B(\u_debounce.last_class [2]),
    .Y(_326_)
  );
  sky130_fd_sc_hd__xnor2_1 _627_ (
    .A(class_result[3]),
    .B(\u_debounce.last_class [3]),
    .Y(_327_)
  );
  sky130_fd_sc_hd__xnor2_1 _628_ (
    .A(class_result[0]),
    .B(\u_debounce.last_class [0]),
    .Y(_328_)
  );
  sky130_fd_sc_hd__xnor2_1 _629_ (
    .A(class_result[1]),
    .B(\u_debounce.last_class [1]),
    .Y(_329_)
  );
  sky130_fd_sc_hd__nand4_1 _630_ (
    .A(_326_),
    .B(_327_),
    .C(_328_),
    .D(_329_),
    .Y(_330_)
  );
  sky130_fd_sc_hd__o41ai_1 _631_ (
    .A1(\u_debounce.last_class [0]),
    .A2(\u_debounce.last_class [1]),
    .A3(\u_debounce.last_class [2]),
    .A4(\u_debounce.last_class [3]),
    .B1(_330_),
    .Y(_331_)
  );
  sky130_fd_sc_hd__nand2_1 _632_ (
    .A(_325_),
    .B(_331_),
    .Y(_332_)
  );
  sky130_fd_sc_hd__a22oi_1 _633_ (
    .A1(irq_n),
    .A2(_324_),
    .B1(_332_),
    .B2(_274_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _634_ (
    .A(cs_n),
    .B(_263_),
    .Y(_333_)
  );
  sky130_fd_sc_hd__nand3_1 _635_ (
    .A(\u_spi.rw_flag ),
    .B(\u_spi.bit_cnt [3]),
    .C(_333_),
    .Y(_334_)
  );
  sky130_fd_sc_hd__mux2_1 _636_ (
    .A0(_212_),
    .A1(\u_spi.rd_is_status ),
    .S(_334_),
    .X(_097_)
  );
  sky130_fd_sc_hd__xnor2_1 _637_ (
    .A(\u_spi.rd_toggle ),
    .B(_334_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor4_1 _638_ (
    .A(\u_spi.rw_flag ),
    .B(cs_n),
    .C(_176_),
    .D(_263_),
    .Y(_335_)
  );
  sky130_fd_sc_hd__mux2_1 _639_ (
    .A0(\u_spi.wr_data_hold [0]),
    .A1(mosi),
    .S(_335_),
    .X(_099_)
  );
  sky130_fd_sc_hd__mux2_1 _640_ (
    .A0(\u_spi.wr_data_hold [1]),
    .A1(\u_spi.shift_in [0]),
    .S(_335_),
    .X(_100_)
  );
  sky130_fd_sc_hd__mux2_1 _641_ (
    .A0(\u_spi.wr_data_hold [2]),
    .A1(\u_spi.shift_in [1]),
    .S(_335_),
    .X(_101_)
  );
  sky130_fd_sc_hd__mux2_1 _642_ (
    .A0(\u_spi.wr_data_hold [3]),
    .A1(\u_spi.shift_in [2]),
    .S(_335_),
    .X(_102_)
  );
  sky130_fd_sc_hd__mux2_1 _643_ (
    .A0(\u_spi.wr_data_hold [4]),
    .A1(\u_spi.shift_in [3]),
    .S(_335_),
    .X(_103_)
  );
  sky130_fd_sc_hd__mux2_1 _644_ (
    .A0(\u_spi.wr_data_hold [5]),
    .A1(\u_spi.shift_in [4]),
    .S(_335_),
    .X(_104_)
  );
  sky130_fd_sc_hd__mux2_1 _645_ (
    .A0(\u_spi.wr_data_hold [6]),
    .A1(\u_spi.shift_in [5]),
    .S(_335_),
    .X(_105_)
  );
  sky130_fd_sc_hd__mux2_1 _646_ (
    .A0(\u_spi.wr_data_hold [7]),
    .A1(\u_spi.shift_in [6]),
    .S(_335_),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_1 _647_ (
    .A0(\u_spi.wr_addr_hold [0]),
    .A1(\u_spi.addr_latched [0]),
    .S(_335_),
    .X(_107_)
  );
  sky130_fd_sc_hd__mux2_1 _648_ (
    .A0(\u_spi.wr_addr_hold [1]),
    .A1(\u_spi.addr_latched [1]),
    .S(_335_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_1 _649_ (
    .A0(\u_spi.wr_addr_hold [2]),
    .A1(\u_spi.addr_latched [2]),
    .S(_335_),
    .X(_109_)
  );
  sky130_fd_sc_hd__mux2_1 _650_ (
    .A0(\u_spi.wr_addr_hold [3]),
    .A1(\u_spi.addr_latched [3]),
    .S(_335_),
    .X(_110_)
  );
  sky130_fd_sc_hd__xor2_1 _651_ (
    .A(\u_spi.wr_toggle ),
    .B(_335_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nor3_1 _652_ (
    .A(cs_n),
    .B(\u_spi.bit_cnt [3]),
    .C(_263_),
    .Y(_336_)
  );
  sky130_fd_sc_hd__mux2_1 _653_ (
    .A0(\u_spi.addr_latched [0]),
    .A1(mosi),
    .S(_336_),
    .X(_112_)
  );
  sky130_fd_sc_hd__mux2_1 _654_ (
    .A0(\u_spi.addr_latched [1]),
    .A1(\u_spi.shift_in [0]),
    .S(_336_),
    .X(_113_)
  );
  sky130_fd_sc_hd__mux2_1 _655_ (
    .A0(\u_spi.addr_latched [2]),
    .A1(\u_spi.shift_in [1]),
    .S(_336_),
    .X(_114_)
  );
  sky130_fd_sc_hd__mux2_1 _656_ (
    .A0(\u_spi.addr_latched [3]),
    .A1(\u_spi.shift_in [2]),
    .S(_336_),
    .X(_115_)
  );
  sky130_fd_sc_hd__mux2_1 _657_ (
    .A0(\u_spi.addr_latched [4]),
    .A1(\u_spi.shift_in [3]),
    .S(_336_),
    .X(_116_)
  );
  sky130_fd_sc_hd__mux2_1 _658_ (
    .A0(\u_spi.addr_latched [5]),
    .A1(\u_spi.shift_in [4]),
    .S(_336_),
    .X(_117_)
  );
  sky130_fd_sc_hd__mux2_1 _659_ (
    .A0(\u_spi.addr_latched [6]),
    .A1(\u_spi.shift_in [5]),
    .S(_336_),
    .X(_118_)
  );
  sky130_fd_sc_hd__mux2_1 _660_ (
    .A0(mosi),
    .A1(\u_spi.shift_in [0]),
    .S(cs_n),
    .X(_120_)
  );
  sky130_fd_sc_hd__mux2_1 _661_ (
    .A0(\u_spi.shift_in [0]),
    .A1(\u_spi.shift_in [1]),
    .S(cs_n),
    .X(_121_)
  );
  sky130_fd_sc_hd__mux2_1 _662_ (
    .A0(\u_spi.shift_in [1]),
    .A1(\u_spi.shift_in [2]),
    .S(cs_n),
    .X(_122_)
  );
  sky130_fd_sc_hd__mux2_1 _663_ (
    .A0(\u_spi.shift_in [2]),
    .A1(\u_spi.shift_in [3]),
    .S(cs_n),
    .X(_123_)
  );
  sky130_fd_sc_hd__mux2_1 _664_ (
    .A0(\u_spi.shift_in [3]),
    .A1(\u_spi.shift_in [4]),
    .S(cs_n),
    .X(_124_)
  );
  sky130_fd_sc_hd__mux2_1 _665_ (
    .A0(\u_spi.shift_in [4]),
    .A1(\u_spi.shift_in [5]),
    .S(cs_n),
    .X(_125_)
  );
  sky130_fd_sc_hd__mux2_1 _666_ (
    .A0(\u_spi.shift_in [5]),
    .A1(\u_spi.shift_in [6]),
    .S(cs_n),
    .X(_126_)
  );
  sky130_fd_sc_hd__xor2_1 _667_ (
    .A(\u_spi.wr_sync2 ),
    .B(\u_spi.wr_sync3 ),
    .X(\u_spi.wr_pulse )
  );
  sky130_fd_sc_hd__mux2_1 _668_ (
    .A0(\u_regfile.wr_data [0]),
    .A1(\u_spi.wr_data_hold [0]),
    .S(\u_spi.wr_pulse ),
    .X(_135_)
  );
  sky130_fd_sc_hd__mux2_1 _669_ (
    .A0(\u_regfile.wr_data [1]),
    .A1(\u_spi.wr_data_hold [1]),
    .S(\u_spi.wr_pulse ),
    .X(_136_)
  );
  sky130_fd_sc_hd__mux2_1 _670_ (
    .A0(\u_regfile.wr_data [2]),
    .A1(\u_spi.wr_data_hold [2]),
    .S(\u_spi.wr_pulse ),
    .X(_137_)
  );
  sky130_fd_sc_hd__mux2_1 _671_ (
    .A0(\u_regfile.wr_data [3]),
    .A1(\u_spi.wr_data_hold [3]),
    .S(\u_spi.wr_pulse ),
    .X(_138_)
  );
  sky130_fd_sc_hd__mux2_1 _672_ (
    .A0(\u_regfile.wr_data [4]),
    .A1(\u_spi.wr_data_hold [4]),
    .S(\u_spi.wr_pulse ),
    .X(_139_)
  );
  sky130_fd_sc_hd__mux2_1 _673_ (
    .A0(\u_regfile.wr_data [5]),
    .A1(\u_spi.wr_data_hold [5]),
    .S(\u_spi.wr_pulse ),
    .X(_140_)
  );
  sky130_fd_sc_hd__mux2_1 _674_ (
    .A0(\u_regfile.wr_data [6]),
    .A1(\u_spi.wr_data_hold [6]),
    .S(\u_spi.wr_pulse ),
    .X(_141_)
  );
  sky130_fd_sc_hd__mux2_1 _675_ (
    .A0(\u_regfile.wr_data [7]),
    .A1(\u_spi.wr_data_hold [7]),
    .S(\u_spi.wr_pulse ),
    .X(_142_)
  );
  sky130_fd_sc_hd__mux2_1 _676_ (
    .A0(\u_regfile.wr_addr [0]),
    .A1(\u_spi.wr_addr_hold [0]),
    .S(\u_spi.wr_pulse ),
    .X(_143_)
  );
  sky130_fd_sc_hd__mux2_1 _677_ (
    .A0(\u_regfile.wr_addr [1]),
    .A1(\u_spi.wr_addr_hold [1]),
    .S(\u_spi.wr_pulse ),
    .X(_144_)
  );
  sky130_fd_sc_hd__mux2_1 _678_ (
    .A0(\u_regfile.wr_addr [2]),
    .A1(\u_spi.wr_addr_hold [2]),
    .S(\u_spi.wr_pulse ),
    .X(_145_)
  );
  sky130_fd_sc_hd__mux2_1 _679_ (
    .A0(\u_regfile.wr_addr [3]),
    .A1(\u_spi.wr_addr_hold [3]),
    .S(\u_spi.wr_pulse ),
    .X(_146_)
  );
  sky130_fd_sc_hd__mux2_1 _680_ (
    .A0(\u_regfile.regs[14] [0]),
    .A1(adc_data_in[0]),
    .S(\u_regfile.adc_done ),
    .X(_147_)
  );
  sky130_fd_sc_hd__mux2_1 _681_ (
    .A0(\u_regfile.regs[14] [1]),
    .A1(adc_data_in[1]),
    .S(\u_regfile.adc_done ),
    .X(_148_)
  );
  sky130_fd_sc_hd__mux2_1 _682_ (
    .A0(\u_regfile.regs[14] [2]),
    .A1(adc_data_in[2]),
    .S(\u_regfile.adc_done ),
    .X(_149_)
  );
  sky130_fd_sc_hd__mux2_1 _683_ (
    .A0(\u_regfile.regs[14] [3]),
    .A1(adc_data_in[3]),
    .S(\u_regfile.adc_done ),
    .X(_150_)
  );
  sky130_fd_sc_hd__mux2_1 _684_ (
    .A0(\u_regfile.regs[14] [4]),
    .A1(adc_data_in[4]),
    .S(\u_regfile.adc_done ),
    .X(_151_)
  );
  sky130_fd_sc_hd__mux2_1 _685_ (
    .A0(\u_regfile.regs[14] [5]),
    .A1(adc_data_in[5]),
    .S(\u_regfile.adc_done ),
    .X(_152_)
  );
  sky130_fd_sc_hd__mux2_1 _686_ (
    .A0(\u_regfile.regs[14] [6]),
    .A1(adc_data_in[6]),
    .S(\u_regfile.adc_done ),
    .X(_153_)
  );
  sky130_fd_sc_hd__mux2_1 _687_ (
    .A0(\u_regfile.regs[14] [7]),
    .A1(adc_data_in[7]),
    .S(\u_regfile.adc_done ),
    .X(_154_)
  );
  sky130_fd_sc_hd__xor2_1 _688_ (
    .A(\u_spi.rd_sync2 ),
    .B(\u_spi.rd_sync3 ),
    .X(_337_)
  );
  sky130_fd_sc_hd__and2_0 _689_ (
    .A(\u_spi.rd_is_status ),
    .B(_337_),
    .X(_174_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _690_ (
    .A(\u_spi.miso_bit ),
    .SLEEP(cs_n),
    .X(miso)
  );
  sky130_fd_sc_hd__nand4_1 _691_ (
    .A(\u_regfile.wr_data [2]),
    .B(\u_regfile.wr_addr [2]),
    .C(\u_regfile.wr_addr [3]),
    .D(_266_),
    .Y(_338_)
  );
  sky130_fd_sc_hd__clkinv_1 _692_ (
    .A(_338_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o21ai_0 _693_ (
    .A1(\u_regfile.adc_done ),
    .A2(_177_),
    .B1(_338_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o21ai_0 _694_ (
    .A1(adc_start),
    .A2(_178_),
    .B1(_338_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__and3_1 _695_ (
    .A(\u_fsm.cnt [0]),
    .B(\u_fsm.cnt [1]),
    .C(\u_fsm.cnt [2]),
    .X(_339_)
  );
  sky130_fd_sc_hd__nor3_1 _696_ (
    .A(\u_fsm.cnt [3]),
    .B(\u_fsm.cnt [4]),
    .C(_339_),
    .Y(_340_)
  );
  sky130_fd_sc_hd__nand3_1 _697_ (
    .A(\u_fsm.cnt [5]),
    .B(\u_fsm.cnt [8]),
    .C(\u_fsm.cnt [9]),
    .Y(_341_)
  );
  sky130_fd_sc_hd__nor3_1 _698_ (
    .A(_273_),
    .B(_340_),
    .C(_341_),
    .Y(_342_)
  );
  sky130_fd_sc_hd__nor2_1 _699_ (
    .A(\u_fsm.cnt [0]),
    .B(_342_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xnor2_1 _700_ (
    .A(\u_fsm.cnt [0]),
    .B(\u_fsm.cnt [1]),
    .Y(_343_)
  );
  sky130_fd_sc_hd__nor2_1 _701_ (
    .A(_342_),
    .B(_343_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _702_ (
    .A1(\u_fsm.cnt [0]),
    .A2(\u_fsm.cnt [1]),
    .B1(\u_fsm.cnt [2]),
    .Y(_344_)
  );
  sky130_fd_sc_hd__nor3_1 _703_ (
    .A(_339_),
    .B(_342_),
    .C(_344_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__xnor2_1 _704_ (
    .A(\u_fsm.cnt [3]),
    .B(_339_),
    .Y(_345_)
  );
  sky130_fd_sc_hd__nor2_1 _705_ (
    .A(_342_),
    .B(_345_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__and3_1 _706_ (
    .A(\u_fsm.cnt [3]),
    .B(\u_fsm.cnt [4]),
    .C(_339_),
    .X(_346_)
  );
  sky130_fd_sc_hd__a21oi_1 _707_ (
    .A1(\u_fsm.cnt [3]),
    .A2(_339_),
    .B1(\u_fsm.cnt [4]),
    .Y(_347_)
  );
  sky130_fd_sc_hd__nor3_1 _708_ (
    .A(_342_),
    .B(_346_),
    .C(_347_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__and2_0 _709_ (
    .A(\u_fsm.cnt [5]),
    .B(_346_),
    .X(_348_)
  );
  sky130_fd_sc_hd__nor2_1 _710_ (
    .A(\u_fsm.cnt [5]),
    .B(_346_),
    .Y(_349_)
  );
  sky130_fd_sc_hd__nor3_1 _711_ (
    .A(_342_),
    .B(_348_),
    .C(_349_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _712_ (
    .A(\u_fsm.cnt [6]),
    .B(_348_),
    .Y(_350_)
  );
  sky130_fd_sc_hd__xnor2_1 _713_ (
    .A(\u_fsm.cnt [6]),
    .B(_348_),
    .Y(_351_)
  );
  sky130_fd_sc_hd__nor2_1 _714_ (
    .A(_342_),
    .B(_351_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__xor2_1 _715_ (
    .A(\u_fsm.cnt [7]),
    .B(_350_),
    .X(_352_)
  );
  sky130_fd_sc_hd__nor2_1 _716_ (
    .A(_342_),
    .B(_352_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__and4_1 _717_ (
    .A(\u_fsm.cnt [8]),
    .B(\u_fsm.cnt [6]),
    .C(\u_fsm.cnt [7]),
    .D(_348_),
    .X(_353_)
  );
  sky130_fd_sc_hd__a31oi_1 _718_ (
    .A1(\u_fsm.cnt [6]),
    .A2(\u_fsm.cnt [7]),
    .A3(_348_),
    .B1(\u_fsm.cnt [8]),
    .Y(_354_)
  );
  sky130_fd_sc_hd__nor3_1 _719_ (
    .A(_342_),
    .B(_353_),
    .C(_354_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xnor2_1 _720_ (
    .A(\u_fsm.cnt [9]),
    .B(_353_),
    .Y(_355_)
  );
  sky130_fd_sc_hd__nor2_1 _721_ (
    .A(_342_),
    .B(_355_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor3b_1 _722_ (
    .A(\u_debounce.debounce_wr ),
    .B(_314_),
    .C_N(\u_debounce.detect_count [0]),
    .Y(_356_)
  );
  sky130_fd_sc_hd__clkinv_1 _723_ (
    .A(_356_),
    .Y(_357_)
  );
  sky130_fd_sc_hd__nand3_1 _724_ (
    .A(\u_debounce.detect_count [0]),
    .B(_331_),
    .C(_357_),
    .Y(_358_)
  );
  sky130_fd_sc_hd__a21oi_1 _725_ (
    .A1(\u_debounce.detect_count [0]),
    .A2(_179_),
    .B1(_274_),
    .Y(_359_)
  );
  sky130_fd_sc_hd__a21oi_1 _726_ (
    .A1(_325_),
    .A2(_358_),
    .B1(_275_),
    .Y(_360_)
  );
  sky130_fd_sc_hd__nor2_1 _727_ (
    .A(_359_),
    .B(_360_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a21oi_1 _728_ (
    .A1(\u_debounce.detect_count [1]),
    .A2(_179_),
    .B1(_274_),
    .Y(_361_)
  );
  sky130_fd_sc_hd__a21o_1 _729_ (
    .A1(_318_),
    .A2(_357_),
    .B1(_332_),
    .X(_362_)
  );
  sky130_fd_sc_hd__a21oi_1 _730_ (
    .A1(_274_),
    .A2(_362_),
    .B1(_361_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a21oi_1 _731_ (
    .A1(_179_),
    .A2(\u_debounce.detect_count [2]),
    .B1(_274_),
    .Y(_363_)
  );
  sky130_fd_sc_hd__o211ai_1 _732_ (
    .A1(_317_),
    .A2(_356_),
    .B1(_331_),
    .C1(_325_),
    .Y(_364_)
  );
  sky130_fd_sc_hd__a21oi_1 _733_ (
    .A1(_274_),
    .A2(_364_),
    .B1(_363_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a21oi_1 _734_ (
    .A1(_179_),
    .A2(\u_debounce.detect_count [3]),
    .B1(_274_),
    .Y(_365_)
  );
  sky130_fd_sc_hd__a21o_1 _735_ (
    .A1(_315_),
    .A2(_357_),
    .B1(_332_),
    .X(_366_)
  );
  sky130_fd_sc_hd__a21oi_1 _736_ (
    .A1(_274_),
    .A2(_366_),
    .B1(_365_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor4bb_1 _737_ (
    .A(adc_done_cnt[1]),
    .B(adc_start),
    .C_N(_307_),
    .D_N(adc_done_cnt[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a22oi_1 _738_ (
    .A1(weights[15]),
    .A2(_182_),
    .B1(_188_),
    .B2(weights[31]),
    .Y(_367_)
  );
  sky130_fd_sc_hd__a222oi_1 _739_ (
    .A1(thresh[7]),
    .A2(_189_),
    .B1(_191_),
    .B2(weights[23]),
    .C1(_192_),
    .C2(weights[7]),
    .Y(_368_)
  );
  sky130_fd_sc_hd__a22oi_1 _740_ (
    .A1(\u_regfile.regs[14] [7]),
    .A2(_185_),
    .B1(_212_),
    .B2(\u_regfile.status_valid ),
    .Y(_369_)
  );
  sky130_fd_sc_hd__a31oi_1 _741_ (
    .A1(_367_),
    .A2(_368_),
    .A3(_369_),
    .B1(_197_),
    .Y(_370_)
  );
  sky130_fd_sc_hd__a21o_1 _742_ (
    .A1(\u_spi.shift_out [7]),
    .A2(_199_),
    .B1(_370_),
    .X(_173_)
  );
  sky130_fd_sc_hd__nor4_1 _743_ (
    .A(\u_fsm.cnt [8]),
    .B(\u_fsm.cnt [9]),
    .C(\u_fsm.cnt [6]),
    .D(\u_fsm.cnt [7]),
    .Y(_371_)
  );
  sky130_fd_sc_hd__nor3b_1 _744_ (
    .A(_371_),
    .B(_271_),
    .C_N(_273_),
    .Y(fsm_evaluate)
  );
  sky130_fd_sc_hd__and2_0 _745_ (
    .A(rst_n),
    .B(_371_),
    .X(fsm_sample)
  );
  sky130_fd_sc_hd__xor2_1 _746_ (
    .A(\u_spi.bit_cnt [0]),
    .B(\u_spi.bit_cnt [1]),
    .X(_378_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _747_ (
    .A1(\u_spi.bit_cnt [0]),
    .A2(\u_spi.bit_cnt [1]),
    .B1(\u_spi.bit_cnt [2]),
    .Y(_372_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _748_ (
    .A(_263_),
    .SLEEP(_372_),
    .X(_378_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _749_ (
    .A(\u_spi.bit_cnt [3]),
    .B(_263_),
    .Y(_378_[3])
  );
  sky130_fd_sc_hd__xor2_1 _750_ (
    .A(clk_div2),
    .B(clk_div4),
    .X(_376_[1])
  );
  sky130_fd_sc_hd__nand3_1 _751_ (
    .A(clk_div2),
    .B(clk_div4),
    .C(clk_div8),
    .Y(_373_)
  );
  sky130_fd_sc_hd__a21oi_1 _752_ (
    .A1(clk_div2),
    .A2(clk_div4),
    .B1(clk_div8),
    .Y(_374_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _753_ (
    .A(_373_),
    .SLEEP(_374_),
    .X(_376_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _754_ (
    .A(clk_div16),
    .B(_373_),
    .Y(_376_[3])
  );
  sky130_fd_sc_hd__clkinv_1 _755_ (
    .A(cs_n),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _756_ (
    .A(cs_n),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _757_ (
    .A(cs_n),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _758_ (
    .A(cs_n),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _759_ (
    .A(cs_n),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _760_ (
    .A(cs_n),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _761_ (
    .A(cs_n),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _762_ (
    .A(cs_n),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _763_ (
    .A(cs_n),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _764_ (
    .A(cs_n),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _765_ (
    .A(cs_n),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _766_ (
    .A(cs_n),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _767_ (
    .A(cs_n),
    .Y(_014_)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _768_ (
    .CLK(clk),
    .D(_015_),
    .Q(adc_chan[0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _769_ (
    .CLK(clk),
    .D(_016_),
    .Q(adc_chan[1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _770_ (
    .CLK(clk),
    .D(_017_),
    .Q(\u_regfile.regs[12] [0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _771_ (
    .CLK(clk),
    .D(_018_),
    .Q(\u_regfile.regs[12] [1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _772_ (
    .CLK(clk),
    .D(_019_),
    .Q(\u_regfile.regs[12] [2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _773_ (
    .CLK(clk),
    .D(_020_),
    .Q(\u_regfile.regs[12] [3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _774_ (
    .CLK(clk),
    .D(_021_),
    .Q(thresh[0]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _775_ (
    .CLK(clk),
    .D(_022_),
    .Q(thresh[1]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _776_ (
    .CLK(clk),
    .D(_023_),
    .Q(thresh[2]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _777_ (
    .CLK(clk),
    .D(_024_),
    .Q(thresh[3]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _778_ (
    .CLK(clk),
    .D(_025_),
    .Q(thresh[4]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _779_ (
    .CLK(clk),
    .D(_026_),
    .Q(thresh[5]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _780_ (
    .CLK(clk),
    .D(_027_),
    .Q(thresh[6]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _781_ (
    .CLK(clk),
    .D(_028_),
    .Q(thresh[7]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _782_ (
    .CLK(clk),
    .D(_029_),
    .Q(weights[24]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _783_ (
    .CLK(clk),
    .D(_030_),
    .Q(weights[25]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _784_ (
    .CLK(clk),
    .D(_031_),
    .Q(weights[26]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _785_ (
    .CLK(clk),
    .D(_032_),
    .Q(weights[27]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _786_ (
    .CLK(clk),
    .D(_033_),
    .Q(weights[28]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _787_ (
    .CLK(clk),
    .D(_034_),
    .Q(weights[29]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _788_ (
    .CLK(clk),
    .D(_035_),
    .Q(weights[30]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _789_ (
    .CLK(clk),
    .D(_036_),
    .Q(weights[31]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _790_ (
    .CLK(clk),
    .D(_037_),
    .Q(weights[16]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _791_ (
    .CLK(clk),
    .D(_038_),
    .Q(weights[17]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _792_ (
    .CLK(clk),
    .D(_039_),
    .Q(weights[18]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _793_ (
    .CLK(clk),
    .D(_040_),
    .Q(weights[19]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _794_ (
    .CLK(clk),
    .D(_041_),
    .Q(weights[20]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _795_ (
    .CLK(clk),
    .D(_042_),
    .Q(weights[21]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _796_ (
    .CLK(clk),
    .D(_043_),
    .Q(weights[22]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _797_ (
    .CLK(clk),
    .D(_044_),
    .Q(weights[23]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _798_ (
    .CLK(clk),
    .D(_045_),
    .Q(weights[8]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _799_ (
    .CLK(clk),
    .D(_046_),
    .Q(weights[9]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _800_ (
    .CLK(clk),
    .D(_047_),
    .Q(weights[10]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _801_ (
    .CLK(clk),
    .D(_048_),
    .Q(weights[11]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _802_ (
    .CLK(clk),
    .D(_049_),
    .Q(weights[12]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _803_ (
    .CLK(clk),
    .D(_050_),
    .Q(weights[13]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _804_ (
    .CLK(clk),
    .D(_051_),
    .Q(weights[14]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _805_ (
    .CLK(clk),
    .D(_052_),
    .Q(weights[15]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _806_ (
    .CLK(clk),
    .D(_053_),
    .Q(weights[0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _807_ (
    .CLK(clk),
    .D(_054_),
    .Q(weights[1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _808_ (
    .CLK(clk),
    .D(_055_),
    .Q(weights[2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _809_ (
    .CLK(clk),
    .D(_056_),
    .Q(weights[3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _810_ (
    .CLK(clk),
    .D(_057_),
    .Q(weights[4]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _811_ (
    .CLK(clk),
    .D(_058_),
    .Q(weights[5]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _812_ (
    .CLK(clk),
    .D(_059_),
    .Q(weights[6]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _813_ (
    .CLK(clk),
    .D(_060_),
    .Q(weights[7]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _814_ (
    .CLK(clk),
    .D(_061_),
    .Q(debounce_val[0]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _815_ (
    .CLK(clk),
    .D(_062_),
    .Q(debounce_val[1]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _816_ (
    .CLK(clk),
    .D(_063_),
    .Q(debounce_val[2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _817_ (
    .CLK(clk),
    .D(_064_),
    .Q(debounce_val[3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _818_ (
    .CLK(clk),
    .D(_065_),
    .Q(tune5[0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _819_ (
    .CLK(clk),
    .D(_066_),
    .Q(tune5[1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _820_ (
    .CLK(clk),
    .D(_067_),
    .Q(tune5[2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _821_ (
    .CLK(clk),
    .D(_068_),
    .Q(tune5[3]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _822_ (
    .CLK(clk),
    .D(_069_),
    .Q(tune4[0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _823_ (
    .CLK(clk),
    .D(_070_),
    .Q(tune4[1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _824_ (
    .CLK(clk),
    .D(_071_),
    .Q(tune4[2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _825_ (
    .CLK(clk),
    .D(_072_),
    .Q(tune4[3]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _826_ (
    .CLK(clk),
    .D(_073_),
    .Q(tune3[0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _827_ (
    .CLK(clk),
    .D(_074_),
    .Q(tune3[1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _828_ (
    .CLK(clk),
    .D(_075_),
    .Q(tune3[2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _829_ (
    .CLK(clk),
    .D(_076_),
    .Q(tune3[3]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _830_ (
    .CLK(clk),
    .D(_077_),
    .Q(tune2[0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _831_ (
    .CLK(clk),
    .D(_078_),
    .Q(tune2[1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _832_ (
    .CLK(clk),
    .D(_079_),
    .Q(tune2[2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _833_ (
    .CLK(clk),
    .D(_080_),
    .Q(tune2[3]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _834_ (
    .CLK(clk),
    .D(_081_),
    .Q(tune1[0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _835_ (
    .CLK(clk),
    .D(_082_),
    .Q(tune1[1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _836_ (
    .CLK(clk),
    .D(_083_),
    .Q(tune1[2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfstp_2 _837_ (
    .CLK(clk),
    .D(_084_),
    .Q(tune1[3]),
    .SET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _838_ (
    .CLK(clk),
    .D(_085_),
    .Q(\u_regfile.status_valid ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _839_ (
    .CLK(clk),
    .D(_169_),
    .Q(\u_regfile.adc_busy ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  sky130_fd_sc_hd__dfrtp_1 _840_ (
    .CLK(clk),
    .D(_086_),
    .Q(\u_debounce.last_class [0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  sky130_fd_sc_hd__dfrtp_1 _841_ (
    .CLK(clk),
    .D(_087_),
    .Q(\u_debounce.last_class [1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  sky130_fd_sc_hd__dfrtp_1 _842_ (
    .CLK(clk),
    .D(_088_),
    .Q(\u_debounce.last_class [2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  sky130_fd_sc_hd__dfrtp_1 _843_ (
    .CLK(clk),
    .D(_089_),
    .Q(\u_debounce.last_class [3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _844_ (
    .CLK(clk),
    .D(_170_),
    .Q(adc_start),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _845_ (
    .CLK(clk),
    .D(_171_),
    .Q(\u_debounce.debounce_wr ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:118.5-133.8" *)
  sky130_fd_sc_hd__dfrtp_1 _846_ (
    .CLK(clk),
    .D(_090_),
    .Q(adc_done_cnt[0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:118.5-133.8" *)
  sky130_fd_sc_hd__dfrtp_1 _847_ (
    .CLK(clk),
    .D(_091_),
    .Q(adc_done_cnt[1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:118.5-133.8" *)
  sky130_fd_sc_hd__dfrtp_1 _848_ (
    .CLK(clk),
    .D(_092_),
    .Q(adc_done_cnt[2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:118.5-133.8" *)
  sky130_fd_sc_hd__dfrtp_1 _849_ (
    .CLK(clk),
    .D(_093_),
    .Q(adc_done_cnt[3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _850_ (
    .CLK(clk),
    .D(_159_),
    .Q(\u_fsm.cnt [0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _851_ (
    .CLK(clk),
    .D(_160_),
    .Q(\u_fsm.cnt [1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _852_ (
    .CLK(clk),
    .D(_161_),
    .Q(\u_fsm.cnt [2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _853_ (
    .CLK(clk),
    .D(_162_),
    .Q(\u_fsm.cnt [3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _854_ (
    .CLK(clk),
    .D(_163_),
    .Q(\u_fsm.cnt [4]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _855_ (
    .CLK(clk),
    .D(_164_),
    .Q(\u_fsm.cnt [5]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _856_ (
    .CLK(clk),
    .D(_165_),
    .Q(\u_fsm.cnt [6]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _857_ (
    .CLK(clk),
    .D(_166_),
    .Q(\u_fsm.cnt [7]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _858_ (
    .CLK(clk),
    .D(_167_),
    .Q(\u_fsm.cnt [8]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:199.7-207.6|../rtl/fsm_classifier.v:38.5-49.8" *)
  sky130_fd_sc_hd__dfrtp_1 _859_ (
    .CLK(clk),
    .D(_168_),
    .Q(\u_fsm.cnt [9]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _860_ (
    .CLK(clk),
    .D(_094_),
    .Q(gain[0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _861_ (
    .CLK(clk),
    .D(_095_),
    .Q(gain[1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  sky130_fd_sc_hd__dfrtp_1 _862_ (
    .CLK(clk),
    .D(_155_),
    .Q(\u_debounce.detect_count [0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  sky130_fd_sc_hd__dfrtp_1 _863_ (
    .CLK(clk),
    .D(_156_),
    .Q(\u_debounce.detect_count [1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  sky130_fd_sc_hd__dfrtp_1 _864_ (
    .CLK(clk),
    .D(_157_),
    .Q(\u_debounce.detect_count [2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  sky130_fd_sc_hd__dfrtp_1 _865_ (
    .CLK(clk),
    .D(_158_),
    .Q(\u_debounce.detect_count [3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:212.7-223.6|../rtl/debounce.v:41.5-86.8" *)
  sky130_fd_sc_hd__dfrtp_1 _866_ (
    .CLK(clk),
    .D(_096_),
    .Q(\u_debounce.irq_assert ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:227.7-234.6|../rtl/clk_divider.v:22.5-27.8" *)
  sky130_fd_sc_hd__dfrtp_1 _867_ (
    .CLK(clk),
    .D(_375_[0]),
    .Q(clk_div2),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:227.7-234.6|../rtl/clk_divider.v:22.5-27.8" *)
  sky130_fd_sc_hd__dfrtp_1 _868_ (
    .CLK(clk),
    .D(_376_[1]),
    .Q(clk_div4),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:227.7-234.6|../rtl/clk_divider.v:22.5-27.8" *)
  sky130_fd_sc_hd__dfrtp_1 _869_ (
    .CLK(clk),
    .D(_376_[2]),
    .Q(clk_div8),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:227.7-234.6|../rtl/clk_divider.v:22.5-27.8" *)
  sky130_fd_sc_hd__dfrtp_1 _870_ (
    .CLK(clk),
    .D(_376_[3]),
    .Q(clk_div16),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _871_ (
    .CLK(clk),
    .D(_172_),
    .Q(\u_regfile.regs[13] [2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _872_ (
    .CLK(sck),
    .D(_097_),
    .Q(\u_spi.rd_is_status )
  );
  (* src = "../rtl/digital_top.v:118.5-133.8" *)
  sky130_fd_sc_hd__dfrtp_1 _873_ (
    .CLK(clk),
    .D(_000_),
    .Q(\u_regfile.adc_done ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _874_ (
    .CLK(sck),
    .D(_098_),
    .Q(\u_spi.rd_toggle )
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _875_ (
    .CLK(sck),
    .D(_099_),
    .Q(\u_spi.wr_data_hold [0])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _876_ (
    .CLK(sck),
    .D(_100_),
    .Q(\u_spi.wr_data_hold [1])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _877_ (
    .CLK(sck),
    .D(_101_),
    .Q(\u_spi.wr_data_hold [2])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _878_ (
    .CLK(sck),
    .D(_102_),
    .Q(\u_spi.wr_data_hold [3])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _879_ (
    .CLK(sck),
    .D(_103_),
    .Q(\u_spi.wr_data_hold [4])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _880_ (
    .CLK(sck),
    .D(_104_),
    .Q(\u_spi.wr_data_hold [5])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _881_ (
    .CLK(sck),
    .D(_105_),
    .Q(\u_spi.wr_data_hold [6])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _882_ (
    .CLK(sck),
    .D(_106_),
    .Q(\u_spi.wr_data_hold [7])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _883_ (
    .CLK(sck),
    .D(_107_),
    .Q(\u_spi.wr_addr_hold [0])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _884_ (
    .CLK(sck),
    .D(_108_),
    .Q(\u_spi.wr_addr_hold [1])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _885_ (
    .CLK(sck),
    .D(_109_),
    .Q(\u_spi.wr_addr_hold [2])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _886_ (
    .CLK(sck),
    .D(_110_),
    .Q(\u_spi.wr_addr_hold [3])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _887_ (
    .CLK(sck),
    .D(_111_),
    .Q(\u_spi.wr_toggle )
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _888_ (
    .CLK(sck),
    .D(_112_),
    .Q(\u_spi.addr_latched [0])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _889_ (
    .CLK(sck),
    .D(_113_),
    .Q(\u_spi.addr_latched [1])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _890_ (
    .CLK(sck),
    .D(_114_),
    .Q(\u_spi.addr_latched [2])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _891_ (
    .CLK(sck),
    .D(_115_),
    .Q(\u_spi.addr_latched [3])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _892_ (
    .CLK(sck),
    .D(_116_),
    .Q(\u_spi.addr_latched [4])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _893_ (
    .CLK(sck),
    .D(_117_),
    .Q(\u_spi.addr_latched [5])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _894_ (
    .CLK(sck),
    .D(_118_),
    .Q(\u_spi.addr_latched [6])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfrtp_1 _895_ (
    .CLK(sck),
    .D(_119_),
    .Q(\u_spi.rw_flag ),
    .RESET_B(_001_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _896_ (
    .CLK(sck),
    .D(_120_),
    .Q(\u_spi.shift_in [0])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _897_ (
    .CLK(sck),
    .D(_121_),
    .Q(\u_spi.shift_in [1])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _898_ (
    .CLK(sck),
    .D(_122_),
    .Q(\u_spi.shift_in [2])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _899_ (
    .CLK(sck),
    .D(_123_),
    .Q(\u_spi.shift_in [3])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _900_ (
    .CLK(sck),
    .D(_124_),
    .Q(\u_spi.shift_in [4])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _901_ (
    .CLK(sck),
    .D(_125_),
    .Q(\u_spi.shift_in [5])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfxtp_1 _902_ (
    .CLK(sck),
    .D(_126_),
    .Q(\u_spi.shift_in [6])
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  sky130_fd_sc_hd__dfrtn_1 _903_ (
    .CLK_N(sck),
    .D(_127_),
    .Q(\u_spi.shift_out [0]),
    .RESET_B(_002_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  sky130_fd_sc_hd__dfrtn_1 _904_ (
    .CLK_N(sck),
    .D(_128_),
    .Q(\u_spi.shift_out [1]),
    .RESET_B(_003_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  sky130_fd_sc_hd__dfrtn_1 _905_ (
    .CLK_N(sck),
    .D(_129_),
    .Q(\u_spi.shift_out [2]),
    .RESET_B(_004_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  sky130_fd_sc_hd__dfrtn_1 _906_ (
    .CLK_N(sck),
    .D(_130_),
    .Q(\u_spi.shift_out [3]),
    .RESET_B(_005_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  sky130_fd_sc_hd__dfrtn_1 _907_ (
    .CLK_N(sck),
    .D(_131_),
    .Q(\u_spi.shift_out [4]),
    .RESET_B(_006_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  sky130_fd_sc_hd__dfrtn_1 _908_ (
    .CLK_N(sck),
    .D(_132_),
    .Q(\u_spi.shift_out [5]),
    .RESET_B(_007_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  sky130_fd_sc_hd__dfrtn_1 _909_ (
    .CLK_N(sck),
    .D(_133_),
    .Q(\u_spi.shift_out [6]),
    .RESET_B(_008_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  sky130_fd_sc_hd__dfrtn_1 _910_ (
    .CLK_N(sck),
    .D(_134_),
    .Q(\u_spi.shift_out [7]),
    .RESET_B(_009_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfrtp_1 _911_ (
    .CLK(sck),
    .D(_377_[0]),
    .Q(\u_spi.bit_cnt [0]),
    .RESET_B(_010_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfrtp_1 _912_ (
    .CLK(sck),
    .D(_378_[1]),
    .Q(\u_spi.bit_cnt [1]),
    .RESET_B(_011_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfrtp_1 _913_ (
    .CLK(sck),
    .D(_378_[2]),
    .Q(\u_spi.bit_cnt [2]),
    .RESET_B(_012_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:63.5-93.8" *)
  sky130_fd_sc_hd__dfrtp_1 _914_ (
    .CLK(sck),
    .D(_378_[3]),
    .Q(\u_spi.bit_cnt [3]),
    .RESET_B(_013_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:100.5-116.8" *)
  sky130_fd_sc_hd__dfrtn_1 _915_ (
    .CLK_N(sck),
    .D(_173_),
    .Q(\u_spi.miso_bit ),
    .RESET_B(_014_)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _916_ (
    .CLK(clk),
    .D(_135_),
    .Q(\u_regfile.wr_data [0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _917_ (
    .CLK(clk),
    .D(_136_),
    .Q(\u_regfile.wr_data [1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _918_ (
    .CLK(clk),
    .D(_137_),
    .Q(\u_regfile.wr_data [2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _919_ (
    .CLK(clk),
    .D(_138_),
    .Q(\u_regfile.wr_data [3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _920_ (
    .CLK(clk),
    .D(_139_),
    .Q(\u_regfile.wr_data [4]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _921_ (
    .CLK(clk),
    .D(_140_),
    .Q(\u_regfile.wr_data [5]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _922_ (
    .CLK(clk),
    .D(_141_),
    .Q(\u_regfile.wr_data [6]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _923_ (
    .CLK(clk),
    .D(_142_),
    .Q(\u_regfile.wr_data [7]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:124.5-134.8" *)
  sky130_fd_sc_hd__dfrtp_1 _924_ (
    .CLK(clk),
    .D(\u_spi.wr_sync2 ),
    .Q(\u_spi.wr_sync3 ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:124.5-134.8" *)
  sky130_fd_sc_hd__dfrtp_1 _925_ (
    .CLK(clk),
    .D(\u_spi.wr_sync1 ),
    .Q(\u_spi.wr_sync2 ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:124.5-134.8" *)
  sky130_fd_sc_hd__dfrtp_1 _926_ (
    .CLK(clk),
    .D(\u_spi.wr_toggle ),
    .Q(\u_spi.wr_sync1 ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:144.5-154.8" *)
  sky130_fd_sc_hd__dfrtp_1 _927_ (
    .CLK(clk),
    .D(\u_spi.rd_sync2 ),
    .Q(\u_spi.rd_sync3 ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:144.5-154.8" *)
  sky130_fd_sc_hd__dfrtp_1 _928_ (
    .CLK(clk),
    .D(\u_spi.rd_sync1 ),
    .Q(\u_spi.rd_sync2 ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:144.5-154.8" *)
  sky130_fd_sc_hd__dfrtp_1 _929_ (
    .CLK(clk),
    .D(\u_spi.rd_toggle ),
    .Q(\u_spi.rd_sync1 ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _930_ (
    .CLK(clk),
    .D(_174_),
    .Q(\u_regfile.status_rd ),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _931_ (
    .CLK(clk),
    .D(_143_),
    .Q(\u_regfile.wr_addr [0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _932_ (
    .CLK(clk),
    .D(_144_),
    .Q(\u_regfile.wr_addr [1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _933_ (
    .CLK(clk),
    .D(_145_),
    .Q(\u_regfile.wr_addr [2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _934_ (
    .CLK(clk),
    .D(_146_),
    .Q(\u_regfile.wr_addr [3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _935_ (
    .CLK(clk),
    .D(_147_),
    .Q(\u_regfile.regs[14] [0]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _936_ (
    .CLK(clk),
    .D(_148_),
    .Q(\u_regfile.regs[14] [1]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _937_ (
    .CLK(clk),
    .D(_149_),
    .Q(\u_regfile.regs[14] [2]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _938_ (
    .CLK(clk),
    .D(_150_),
    .Q(\u_regfile.regs[14] [3]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _939_ (
    .CLK(clk),
    .D(_151_),
    .Q(\u_regfile.regs[14] [4]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _940_ (
    .CLK(clk),
    .D(_152_),
    .Q(\u_regfile.regs[14] [5]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _941_ (
    .CLK(clk),
    .D(_153_),
    .Q(\u_regfile.regs[14] [6]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:163.7-188.6|../rtl/reg_file.v:80.5-161.8" *)
  sky130_fd_sc_hd__dfrtp_1 _942_ (
    .CLK(clk),
    .D(_154_),
    .Q(\u_regfile.regs[14] [7]),
    .RESET_B(rst_n)
  );
  (* src = "../rtl/digital_top.v:145.7-158.6|../rtl/spi_slave.v:162.5-182.8" *)
  sky130_fd_sc_hd__dfrtp_1 _943_ (
    .CLK(clk),
    .D(\u_spi.wr_pulse ),
    .Q(\u_regfile.wr_en ),
    .RESET_B(rst_n)
  );
  assign _375_[3:1] = { clk_div16, clk_div8, clk_div4 };
  assign _376_[0] = _375_[0];
  assign _377_[3:1] = \u_spi.bit_cnt [3:1];
  assign _378_[0] = _377_[0];
  assign \u_regfile.regs[12] [7:4] = 4'h0;
  assign { \u_regfile.regs[13] [7:4], \u_regfile.regs[13] [1:0] } = { 4'h0, adc_chan };
endmodule
